import { useState, useEffect, useRef, useCallback, forwardRef, useImperativeHandle } from 'react'
import { useParams, useLocation, Link } from 'react-router-dom'
import LinkAnalysisModal, { type PersonLinkData } from '../components/LinkAnalysisModal'
import Chatbot from './Chatbot'
import { useVideoCache } from '../contexts/VideoCache'

const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:5000'

function toTitleCase(s: string): string {
  return s.replace(/\b\w/g, (c) => c.toUpperCase())
}

/** Analysis generated by API and stored in video metadata (video_analysis). */
type VideoAnalysisData = {
  title: string
  description: string
  categories: string[]
  topics: string[]
  riskLevel: 'high' | 'medium' | 'low'
  risks: Array<{ label: string; severity: 'high' | 'medium' | 'low'; timestamp?: string | null }>
  transcript: Array<{ time: string; text: string }>
}

const DEFAULT_VIDEO_PLACEHOLDER: VideoAnalysisData = {
  title: '—',
  description: 'No analysis generated yet. Use "Generate analysis" to create a description, categories, topics, risks, and transcript for this video.',
  categories: [],
  topics: [],
  riskLevel: 'medium',
  risks: [],
  transcript: [],
}

/** From API: /api/videos/:id/insights */
type PersonInsight = {
  entity_id: string
  name: string
  avatar: string
  percent: number
  face_snap_base64?: string | null
  /** Face cropped from this video (from frame at best clip); preferred for display */
  face_from_video_base64?: string | null
  clips: Array<{ start: number; end: number; score: number }>
}
type ObjectInsight = {
  object: string
  timestamp: number
  frame_url?: string
  /** Normalized 0–1 bounding box from Rekognition (left, top, width, height) */
  bbox?: { left: number; top: number; width: number; height: number }
}
type VideoInsights = {
  people: PersonInsight[]
  mentioned: string[]
  objects: ObjectInsight[]
  link_data_by_entity: Record<string, PersonLinkData>
  video_duration_sec: number
}


function Button({
  children,
  variant = 'black',
  size = 'regular',
  onClick,
  className = '',
}: {
  children: React.ReactNode
  variant?: 'black' | 'white' | 'gray' | 'ghosted-black' | 'black-outline'
  size?: 'small' | 'regular' | 'medium'
  onClick?: () => void
  className?: string
}) {
  const sizeMap = {
    small: 'h-7 px-2 py-1.5 text-sm rounded-md gap-1',
    regular: 'h-8 px-3 py-1.5 text-base rounded-[9.6px] gap-1',
    medium: 'h-10 px-[18px] py-2 text-lg rounded-lg gap-1',
  }
  const variantMap = {
    black:
      'bg-brand-charcoal text-brand-white hover:bg-gray-300 hover:text-brand-charcoal',
    white:
      'bg-surface text-brand-charcoal hover:bg-gray-300 hover:text-brand-charcoal',
    gray:
      'bg-gray-200 text-brand-charcoal hover:bg-gray-400 hover:text-brand-charcoal',
    'ghosted-black':
      'bg-transparent text-brand-charcoal hover:bg-brand-charcoal/[0.08]',
    'black-outline':
      'bg-transparent text-brand-charcoal border border-brand-charcoal hover:bg-gray-300',
  }

  return (
    <button
      type="button"
      onClick={onClick}
      className={`inline-flex items-center justify-center font-brand transition-all duration-200 ${sizeMap[size]} ${variantMap[variant]} ${className}`}
    >
      {children}
    </button>
  )
}

const SECTION_UNDERLINE_MAP: Record<string, string> = {
  'bg-accent': 'border-accent',
  'bg-product-generate': 'border-product-generate',
  'bg-product-embed': 'border-product-embed',
  'bg-product-search': 'border-product-search',
  'bg-error': 'border-error',
}

function Section({
  title,
  badge,
  color,
  children,
}: {
  title: string
  badge?: number
  color: string
  children: React.ReactNode
}) {
  const badgeBgMap: Record<string, string> = {
    'bg-accent': 'bg-accent/10 text-accent',
    'bg-product-generate': 'bg-product-generate/10 text-product-generate',
    'bg-product-embed': 'bg-product-embed/10 text-product-embed',
    'bg-product-search': 'bg-product-search/10 text-product-search',
    'bg-error': 'bg-error/10 text-error',
  }
  const badgeStyle = badgeBgMap[color] ?? 'bg-gray-100 text-gray-500'
  const underlineStyle = SECTION_UNDERLINE_MAP[color] ?? 'border-gray-300'

  return (
    <div className="py-3 sm:py-4">
      <div className={`w-fit border-b-2 pb-1.5 ${underlineStyle}`}>
        <div className="flex items-center gap-2">
          <h3 className="text-base font-semibold text-text-primary">{title}</h3>
          {badge !== undefined && (
            <span className={`text-[11px] font-medium px-1.5 py-0.5 rounded-full ${badgeStyle}`}>{badge}</span>
          )}
        </div>
      </div>
      <div className="mt-3">{children}</div>
    </div>
  )
}

function Avatar({ initials, size = 'md', imageBase64 }: { initials: string; size?: 'sm' | 'md'; imageBase64?: string | null }) {
  const dim = size === 'sm' ? 'w-9 h-9 text-xs' : 'w-12 h-12 text-sm'
  if (imageBase64) {
    return (
      <div className={`${dim} rounded-full overflow-hidden bg-gray-200 shrink-0 ring-1 ring-gray-300`}>
        <img src={`data:image/png;base64,${imageBase64}`} alt="" className="w-full h-full object-cover" />
      </div>
    )
  }
  return (
    <div className={`${dim} rounded-full bg-gray-300 text-gray-600 font-medium flex items-center justify-center shrink-0`}>
      {initials}
    </div>
  )
}

function Tag({ label, active = false }: { label: string; active?: boolean }) {
  return (
    <span
      className={`inline-block px-3 py-1 rounded-full text-sm border cursor-pointer transition-colors duration-200 ${
        active
          ? 'bg-brand-charcoal text-brand-white border-brand-charcoal'
          : 'bg-surface text-gray-700 border-gray-300 hover:border-gray-400'
      }`}
    >
      {label}
    </span>
  )
}

function RiskBadge({ severity }: { severity: 'high' | 'medium' | 'low' }) {
  const styles = {
    high: 'bg-error/10 text-error border-error/20',
    medium: 'bg-warning/10 text-warning border-warning/20',
    low: 'bg-success/10 text-success border-success/20',
  }
  return (
    <span className={`inline-flex items-center px-2 py-0.5 rounded-sm text-xs font-medium border ${styles[severity]}`}>
      {severity.charAt(0).toUpperCase() + severity.slice(1)}
    </span>
  )
}

/* Overall risk indicator                                              */
function RiskLevel({ level }: { level: 'high' | 'medium' | 'low' }) {
  const config = {
    high: { label: 'High Risk', bg: 'bg-error/10', text: 'text-error', dot: 'bg-error' },
    medium: { label: 'Medium Risk', bg: 'bg-warning/10', text: 'text-warning', dot: 'bg-warning' },
    low: { label: 'Low Risk', bg: 'bg-success/10', text: 'text-success', dot: 'bg-success' },
  }
  const c = config[level]
  return (
    <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-sm font-medium ${c.bg} ${c.text}`}>
      <span className={`w-2 h-2 rounded-full ${c.dot}`} />
      {c.label}
    </span>
  )
}

function formatTimelineTime(totalSeconds: number): string {
  const m = Math.floor(totalSeconds / 60)
  const s = Math.floor(totalSeconds % 60)
  return `${m}:${s.toString().padStart(2, '0')}`
}

function TimelineBar({
  segments,
  durationSeconds,
}: {
  segments: number[]
  durationSeconds?: number
}) {
  const n = segments.length
  const duration = durationSeconds ?? (n * 13)
  const segmentDuration = duration / n
  const showMidTick = duration > 90
  const midTime = showMidTick ? Math.round((duration / 2) / 30) * 30 : 0

  return (
    <div className="mt-3 w-full">
      <p className="mb-1.5 text-xs font-medium text-gray-500">Presence in video</p>
      <div className="flex gap-0.5 w-full h-2.5 rounded-sm overflow-hidden bg-gray-100">
        {segments.map((filled, i) => (
          <div
            key={i}
            className={`flex-1 min-w-0 rounded-sm ${filled ? 'timeline-embed-gradient' : 'bg-gray-200'}`}
            style={
              filled
                ? {
                    backgroundSize: `${n * 100}% 100%`,
                    backgroundPosition: `${(-i * 100) / (n || 1)}% 0`,
                  }
                : undefined
            }
            title={`${formatTimelineTime(i * segmentDuration)} – ${formatTimelineTime((i + 1) * segmentDuration)}`}
          />
        ))}
      </div>
      <div
        className={`mt-1 w-full text-[11px] text-gray-500 tabular-nums ${showMidTick ? 'grid grid-cols-3 items-center' : 'flex justify-between'}`}
        aria-hidden
      >
        <span>0:00</span>
        {showMidTick ? <span className="text-center">{formatTimelineTime(midTime)}</span> : null}
        <span className={showMidTick ? 'text-right' : ''}>{formatTimelineTime(duration)}</span>
      </div>
    </div>
  )
}

function PdfReportModal({
  open,
  onClose,
  videoId,
  title,
  riskLevel,
  risks,
}: {
  open: boolean
  onClose: () => void
  videoId: string
  title: string
  riskLevel: string
  risks: Array<{ label: string; severity: string }>
}) {
  if (!open) return null

  function handleDownload() {
    const blob = new Blob(['Compliance report for ' + videoId], { type: 'application/pdf' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `compliance-report-${videoId}.pdf`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center p-3 sm:p-4">
      <div className="absolute inset-0 bg-brand-charcoal/40 backdrop-blur-sm" onClick={onClose} aria-hidden />
      <div
        className="relative w-full max-w-2xl max-h-[90vh] flex flex-col rounded-xl border border-border bg-surface shadow-xl"
        role="dialog"
        aria-modal="true"
        aria-labelledby="pdf-report-title"
      >
        <div className="flex items-center justify-between border-b border-border px-5 py-4 shrink-0">
          <h2 id="pdf-report-title" className="text-lg font-semibold text-text-primary">
            PDF Report
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="p-2 rounded-lg text-text-tertiary hover:bg-card hover:text-text-primary transition-colors"
            aria-label="Close"
          >
            <svg className="w-5 h-5" viewBox="0 0 12 12" fill="currentColor">
              <path d="M6.02051 5.31348L8.9668 2.36719L9.67383 3.07422L6.72754 6.02051L9.65332 8.94629L8.94629 9.65332L6.02051 6.72754L3.07422 9.67383L2.36719 8.9668L5.31348 6.02051L2.34668 3.05371L3.05371 2.34668L6.02051 5.31348Z" />
              <path fillRule="evenodd" clipRule="evenodd" d="M8.40039 0C10.3883 0.000211285 11.9998 1.61169 12 3.59961V8.40039C11.9998 10.3883 10.3883 11.9998 8.40039 12H3.59961C1.61169 11.9998 0.000211285 10.3883 0 8.40039V3.59961C0.000211156 1.61169 1.61169 0.000211157 3.59961 0H8.40039ZM3.59961 1C2.16398 1.00021 1.00021 2.16398 1 3.59961V8.40039C1.00021 9.83602 2.16398 10.9998 3.59961 11H8.40039C9.83602 10.9998 10.9998 9.83602 11 8.40039V3.59961C10.9998 2.16398 9.83602 1.00021 8.40039 1H3.59961Z" />
            </svg>
          </button>
        </div>
        <div className="flex-1 overflow-y-auto p-5 bg-card">
          <div className="bg-surface rounded-lg border border-border shadow-sm p-6 text-text-primary">
            <p className="text-xs text-text-tertiary uppercase tracking-wider mb-2">Compliance Intelligence Report</p>
            <h3 className="text-lg font-semibold text-text-primary mb-1">{title}</h3>
            <p className="text-sm text-text-secondary mb-4">Video ID: {videoId} · Generated: {new Date().toLocaleDateString()}</p>
            <div className="border-t border-border pt-4 mb-4">
              <p className="text-xs font-medium text-text-tertiary uppercase mb-2">Risk level</p>
              <p className="text-sm font-medium capitalize">{riskLevel}</p>
            </div>
            <div className="border-t border-border pt-4">
              <p className="text-xs font-medium text-gray-500 uppercase mb-2">Key findings</p>
              <ul className="space-y-1.5 text-sm">
                {risks.map((r, i) => (
                  <li key={i} className="flex justify-between gap-2">
                    <span>{r.label}</span>
                    <span className={`shrink-0 text-xs font-medium capitalize ${r.severity === 'high' ? 'text-error' : r.severity === 'medium' ? 'text-warning' : 'text-success'}`}>{r.severity}</span>
                  </li>
                ))}
              </ul>
            </div>
            <p className="text-xs text-text-tertiary mt-6">This is a preview. Download for full PDF.</p>
          </div>
        </div>
        <div className="flex flex-wrap items-center justify-end gap-2 border-t border-border px-3 sm:px-5 py-4 shrink-0 bg-surface rounded-b-xl">
          <Button variant="ghosted-black" size="regular" onClick={onClose}>Close</Button>
          <Button variant="black" size="regular" onClick={handleDownload}>Download PDF</Button>
        </div>
      </div>
    </div>
  )
}

type PersonEntry = { id: string; name: string; avatar: string; percent: number; face_snap_base64?: string | null; face_from_video_base64?: string | null; clips: Array<{ start: number; end: number; score: number }> }

type ClipMatch = { start: number; end: number; score: number; type: string }

function fmtSec(seconds: number): string {
  if (!Number.isFinite(seconds) || seconds < 0) return '—'
  const h = Math.floor(seconds / 3600)
  const m = Math.floor((seconds % 3600) / 60)
  const s = Math.floor(seconds % 60)
  if (h > 0) return `${h}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`
  return `${m}:${s.toString().padStart(2, '0')}`
}

/** Parse "M:SS" or "H:MM:SS" to seconds for video seek. */
function parseTimestampToSeconds(timestamp: string): number {
  const s = String(timestamp).trim()
  if (!s) return NaN
  const parts = s.split(':').map((p) => parseInt(p, 10))
  if (parts.some((n) => !Number.isFinite(n) || n < 0)) return NaN
  if (parts.length === 2) return parts[0] * 60 + parts[1]
  if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2]
  if (parts.length === 1) return parts[0]
  return NaN
}

function clipRelevance(clips: ClipMatch[]): { label: string; color: string } {
  if (!clips.length) return { label: '', color: '' }
  const best = Math.max(...clips.map((c) => c.score))
  if (best >= 0.10) return { label: 'Highest', color: 'bg-emerald-100 text-emerald-800 border-emerald-300' }
  if (best >= 0.08) return { label: 'High', color: 'bg-green-100 text-green-800 border-green-300' }
  if (best >= 0.06) return { label: 'Medium', color: 'bg-yellow-100 text-yellow-800 border-yellow-300' }
  return { label: 'Low', color: 'bg-red-50 text-red-700 border-red-200' }
}

function clipScoreColor(score: number): string {
  if (score >= 0.10) return 'text-emerald-700'
  if (score >= 0.08) return 'text-green-700'
  if (score >= 0.06) return 'text-yellow-700'
  return 'text-red-600'
}

function clipScoreBg(score: number): string {
  if (score >= 0.10) return 'bg-emerald-50 border-emerald-100'
  if (score >= 0.08) return 'bg-green-50 border-green-100'
  if (score >= 0.06) return 'bg-yellow-50 border-yellow-100'
  return 'bg-red-50 border-red-100'
}

function clipScoreLabel(score: number): string {
  if (score >= 0.10) return 'Highest'
  if (score >= 0.08) return 'High'
  if (score >= 0.06) return 'Medium'
  return 'Low'
}

interface VideoPlayerHandle {
  seekTo: (time: number) => void
}

const StableVideoPlayer = forwardRef<VideoPlayerHandle, {
  src: string
  className?: string
  controls?: boolean
}>(function StableVideoPlayer({ src, className = '', controls = true }, ref) {
  const videoRef = useRef<HTMLVideoElement>(null)
  const currentSrcRef = useRef('')
  const [status, setStatus] = useState<'idle' | 'loading' | 'ready' | 'error'>('idle')

  useImperativeHandle(ref, () => ({
    seekTo(time: number) {
      const el = videoRef.current
      if (el) {
        el.currentTime = time
        el.play().catch(() => {})
      }
    },
  }))

  useEffect(() => {
    const el = videoRef.current
    if (!el || !src) {
      if (!src) setStatus('idle')
      return
    }
    if (currentSrcRef.current === src) return
    currentSrcRef.current = src
    setStatus('loading')
    el.src = src
    el.load()
  }, [src])

  const handleCanPlay = useCallback(() => setStatus('ready'), [])
  const handleError = useCallback(() => {
    if (currentSrcRef.current) setStatus('error')
  }, [])
  const handleRetry = useCallback(() => {
    const el = videoRef.current
    if (el && currentSrcRef.current) {
      setStatus('loading')
      el.load()
    }
  }, [])

  return (
    <div className="relative aspect-video bg-gray-800 flex items-center justify-center overflow-hidden">
      {src ? (
        <video
          ref={videoRef}
          className={`w-full h-full object-cover ${status === 'ready' ? 'opacity-100' : 'opacity-0'} transition-opacity duration-300 ${className}`}
          controls={controls}
          playsInline
          preload="metadata"
          onCanPlay={handleCanPlay}
          onError={handleError}
        />
      ) : null}

      {(status === 'idle' || status === 'loading') && (
        <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
          {status === 'loading' ? (
            <div className="w-10 h-10 border-3 border-white/30 border-t-white rounded-full animate-spin" />
          ) : (
            <div className="w-14 h-14 rounded-full bg-surface/20 backdrop-blur-sm flex items-center justify-center">
              <svg className="w-7 h-7 text-brand-white ml-1" fill="currentColor" viewBox="0 0 24 24">
                <path d="M8 5v14l11-7z" />
              </svg>
            </div>
          )}
        </div>
      )}

      {status === 'error' && (
        <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 pointer-events-auto">
          <svg className="w-8 h-8 text-white/50" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 9v3m0 3h.01M5.07 19h13.86c1.54 0 2.5-1.67 1.73-3L13.73 4c-.77-1.33-2.69-1.33-3.46 0L3.34 16c-.77 1.33.19 3 1.73 3z" />
          </svg>
          <p className="text-sm text-white/60">Video failed to load</p>
          <button
            type="button"
            onClick={handleRetry}
            className="px-3 py-1.5 rounded-lg bg-white/10 hover:bg-white/20 text-sm text-white/80 transition-colors"
          >
            Retry
          </button>
        </div>
      )}
    </div>
  )
})

export default function VideoAnalysis() {
  const { videoId } = useParams<{ videoId: string }>()
  const location = useLocation()
  const navState = (location.state || {}) as { searchClips?: ClipMatch[]; searchScore?: number; searchQuery?: string }
  const { getVideo, refresh: refreshCache } = useVideoCache()

  const { searchClips, searchQuery, hasSearchContext } = (() => {
    if (navState.searchClips && navState.searchClips.length > 0) {
      return {
        searchClips: navState.searchClips,
        searchQuery: navState.searchQuery || '',
        hasSearchContext: true,
      }
    }
    if (videoId) {
      try {
        const raw = sessionStorage.getItem(`vc_clips_${videoId}`)
        if (raw) {
          const parsed = JSON.parse(raw)
          if (Array.isArray(parsed.clips) && parsed.clips.length > 0) {
            return {
              searchClips: parsed.clips as ClipMatch[],
              searchQuery: (parsed.query || '') as string,
              hasSearchContext: false,
            }
          }
        }
      } catch { /* ignore */ }
    }
    return { searchClips: [] as ClipMatch[], searchQuery: '', hasSearchContext: false }
  })()
  const cachedVideo = videoId ? getVideo(videoId) : undefined
  const videoTitle = cachedVideo?.metadata?.filename || videoId || ''

  const rawAnalysis = cachedVideo?.metadata?.video_analysis as VideoAnalysisData | undefined
  const videoAnalysis: VideoAnalysisData = rawAnalysis?.title
    ? {
        title: rawAnalysis.title,
        description: rawAnalysis.description ?? '',
        categories: Array.isArray(rawAnalysis.categories) ? rawAnalysis.categories : [],
        topics: Array.isArray(rawAnalysis.topics) ? rawAnalysis.topics : [],
        riskLevel: ['high', 'medium', 'low'].includes(rawAnalysis.riskLevel) ? rawAnalysis.riskLevel : 'medium',
        risks: Array.isArray(rawAnalysis.risks)
          ? rawAnalysis.risks.map((r: any) => ({
              label: r?.label ?? '',
              severity: ['high', 'medium', 'low'].includes(r?.severity) ? r.severity : 'medium',
              timestamp: r?.timestamp ?? r?.time ?? null,
            }))
          : [],
        transcript: Array.isArray(rawAnalysis.transcript)
          ? rawAnalysis.transcript.map((t: any) => ({ time: String(t?.time ?? '0:00'), text: String(t?.text ?? '') }))
          : [],
      }
    : DEFAULT_VIDEO_PLACEHOLDER

  const [generatingAnalysis, setGeneratingAnalysis] = useState(false)
  const [analysisError, setAnalysisError] = useState<string | null>(null)

  async function generateAnalysis() {
    if (!videoId) return
    setAnalysisError(null)
    setGeneratingAnalysis(true)
    try {
      const res = await fetch(`${API_BASE}/api/videos/${encodeURIComponent(videoId)}/analysis`, { method: 'POST' })
      const data = await res.json().catch(() => ({}))
      if (!res.ok) {
        setAnalysisError(data?.error ?? `HTTP ${res.status}`)
        return
      }
      await refreshCache(true)
    } catch (e: any) {
      setAnalysisError(e?.message ?? 'Request failed')
    } finally {
      setGeneratingAnalysis(false)
    }
  }

  const stableUrlRef = useRef<{ id: string; url: string }>({ id: '', url: '' })
  const videoStreamUrl = (() => {
    const freshUrl = cachedVideo?.stream_url || ''
    if (videoId && videoId !== stableUrlRef.current.id) {
      stableUrlRef.current = { id: videoId, url: freshUrl }
    } else if (videoId && !stableUrlRef.current.url && freshUrl) {
      stableUrlRef.current = { id: videoId, url: freshUrl }
    }
    return stableUrlRef.current.url
  })()

  const [insights, setInsights] = useState<VideoInsights | null>(null)
  const [insightsLoading, setInsightsLoading] = useState(false)
  const [insightsError, setInsightsError] = useState<string | null>(null)
  const [generatingInsights, setGeneratingInsights] = useState(false)

  const people: PersonEntry[] = insights?.people?.map((p) => ({
    id: p.entity_id,
    name: p.name,
    avatar: p.avatar,
    percent: p.percent,
    face_snap_base64: p.face_snap_base64,
    face_from_video_base64: p.face_from_video_base64,
    clips: p.clips || [],
  })) ?? []
  const mentionedNames: string[] = insights?.mentioned ?? []
  const objectsList: ObjectInsight[] = insights?.objects ?? []
  const linkDataByEntity: Record<string, PersonLinkData> = insights?.link_data_by_entity ?? {}
  const videoDurationSec = insights?.video_duration_sec ?? 0

  const [selectedPerson, setSelectedPerson] = useState<PersonEntry | null>(null)
  useEffect(() => {
    if (people.length > 0 && (!selectedPerson || !people.find((p) => p.id === selectedPerson.id)))
      setSelectedPerson(people[0])
    else if (people.length === 0) setSelectedPerson(null)
  }, [insights?.people?.length, insights?.people?.map((p) => p.entity_id).join(',')])

  const [activeObjectIdx, setActiveObjectIdx] = useState(0)
  const [reportModalOpen, setReportModalOpen] = useState(false)
  const [linkAnalysisPersonId, setLinkAnalysisPersonId] = useState<string | null>(null)
  const [editingPersonId, setEditingPersonId] = useState<string | null>(null)
  const [editName, setEditName] = useState('')
  const [showAllTranscript, setShowAllTranscript] = useState(false)
  const playerRef = useRef<VideoPlayerHandle>(null)
  const sidebarPlayerRef = useRef<VideoPlayerHandle>(null)
  const [chatPanelOpen, setChatPanelOpen] = useState(false)
  const [activeClipIdx, setActiveClipIdx] = useState<number | null>(null)
  const [clipThumbnails, setClipThumbnails] = useState<Record<number, string>>({})
  const thumbnailVideoRef = useRef<HTMLVideoElement>(null)
  const thumbnailCanvasRef = useRef<HTMLCanvasElement>(null)
  const captureIndexRef = useRef(0)
  const [isLgViewport, setIsLgViewport] = useState(() => typeof window !== 'undefined' && window.matchMedia('(min-width: 1024px)').matches)

  useEffect(() => {
    if (videoId && !cachedVideo) refreshCache(true)
  }, [videoId, cachedVideo, refreshCache])

  useEffect(() => {
    if (!videoId) return
    setInsightsLoading(true)
    setInsightsError(null)
    fetch(`${API_BASE}/api/videos/${encodeURIComponent(videoId)}/insights`)
      .then((r) => {
        if (r.ok) return r.json()
        if (r.status === 404) return null
        throw new Error(r.statusText || 'Failed to fetch insights')
      })
      .then((data) => {
        if (data?.insights) setInsights(data.insights)
        else setInsights(null)
      })
      .catch((e) => {
        setInsightsError(e?.message ?? 'Failed to load insights')
        setInsights(null)
      })
      .finally(() => setInsightsLoading(false))
  }, [videoId])

  async function generateInsights() {
    if (!videoId) return
    setInsightsError(null)
    setGeneratingInsights(true)
    try {
      const res = await fetch(`${API_BASE}/api/videos/${encodeURIComponent(videoId)}/insights`, { method: 'POST' })
      const data = await res.json().catch(() => ({}))
      if (!res.ok) throw new Error(data?.error ?? `HTTP ${res.status}`)
      if (data.insights) setInsights(data.insights)
    } catch (e: any) {
      setInsightsError(e?.message ?? 'Failed to generate insights')
    } finally {
      setGeneratingInsights(false)
    }
  }

  useEffect(() => {
    const mq = window.matchMedia('(min-width: 1024px)')
    const handler = () => setIsLgViewport(mq.matches)
    mq.addEventListener('change', handler)
    return () => mq.removeEventListener('change', handler)
  }, [])

  // Generate thumbnails for each clip (frame at clip.start)
  useEffect(() => {
    if (!videoStreamUrl || searchClips.length === 0) {
      setClipThumbnails({})
      return
    }
    const video = thumbnailVideoRef.current
    const canvas = thumbnailCanvasRef.current
    if (!video || !canvas) return
    const ctx = canvas.getContext('2d')
    if (!ctx) return

    setClipThumbnails({})
    const clips = searchClips

    const onSeeked = () => {
      const i = captureIndexRef.current
      if (i >= clips.length) return
      if (video.videoWidth && video.videoHeight) {
        canvas.width = video.videoWidth
        canvas.height = video.videoHeight
        ctx.drawImage(video, 0, 0)
        try {
          const dataUrl = canvas.toDataURL('image/jpeg', 0.85)
          setClipThumbnails((prev) => ({ ...prev, [i]: dataUrl }))
        } catch {
          // ignore
        }
      }
      const next = i + 1
      if (next < clips.length) {
        captureIndexRef.current = next
        video.currentTime = clips[next].start
      }
    }

    const onLoadedData = () => {
      captureIndexRef.current = 0
      video.currentTime = clips[0].start
    }

    video.addEventListener('seeked', onSeeked)
    video.addEventListener('loadeddata', onLoadedData, { once: true })
    video.src = videoStreamUrl
    video.load()

    return () => {
      video.removeEventListener('seeked', onSeeked)
      video.removeEventListener('loadeddata', onLoadedData)
      video.src = ''
    }
  }, [videoStreamUrl, searchClips])

  function startEditing(p: PersonEntry) {
    setEditingPersonId(p.id)
    setEditName(p.name)
  }

  function commitEdit(personId: string) {
    const trimmed = editName.trim()
    if (trimmed && insights?.people) {
      const updated = insights.people.map((p) =>
        p.entity_id === personId
          ? { ...p, name: trimmed, avatar: trimmed.split(' ').map((w) => w[0]?.toUpperCase() ?? '').join('').slice(0, 2) }
          : p
      )
      setInsights((prev) => (prev ? { ...prev, people: updated } : null))
      if (selectedPerson?.id === personId) {
        setSelectedPerson((prev) => (prev ? { ...prev, name: trimmed, avatar: trimmed.split(' ').map((w) => w[0]?.toUpperCase() ?? '').join('').slice(0, 2) } : null))
      }
    }
    setEditingPersonId(null)
    setEditName('')
  }

  const timelineSegments: number[] = (() => {
    const dur = videoDurationSec || 60
    const n = 20
    const segDur = dur / n
    const clips = selectedPerson?.clips ?? []
    return Array.from({ length: n }, (_, i) => {
      const t0 = i * segDur
      const t1 = (i + 1) * segDur
      return clips.some((c) => c.end > t0 && c.start < t1) ? 1 : 0
    })
  })()

  return (
    <div className="flex flex-col h-full">
      <div className="px-3 sm:px-6 pt-4 sm:pt-5 pb-3 flex flex-wrap items-center justify-between gap-3 shrink-0">
        <div className="flex items-center gap-2 sm:gap-3 text-sm min-w-0 flex-1">
          <Link
            to="/"
            className="inline-flex items-center gap-2 px-3 sm:px-4 py-2 rounded-full border border-border bg-surface text-sm font-medium text-text-secondary hover:border-accent hover:bg-accent/5 hover:text-text-primary transition-colors shrink-0 no-underline"
            aria-label="Back to search"
          >
            <svg className="w-4 h-4 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
              <path d="M19 12H5M12 19l-7-7 7-7" />
            </svg>
            Back to search
          </Link>
          <span className="text-gray-400 shrink-0 hidden sm:inline" aria-hidden>/</span>
          <span className="text-gray-700 font-medium truncate">{videoTitle || `Video ${videoId}`}</span>
        </div>
        <button
          type="button"
          onClick={() => setChatPanelOpen(true)}
          className="inline-flex items-center gap-2 px-3 sm:px-4 py-2 rounded-full border border-border bg-surface text-sm font-medium text-text-secondary hover:border-accent hover:bg-accent/5 hover:text-text-primary transition-colors shrink-0"
        >
          <svg className="w-4 h-4 text-gray-500 shrink-0" viewBox="0 0 12 12.0376" fill="currentColor" aria-hidden>
            <path fillRule="evenodd" clipRule="evenodd" d="M8.8 1H3.2C1.98497 1 1 1.98497 1 3.2V6.13333C1 7.34836 1.98497 8.33333 3.2 8.33333H3.92451C4.32261 8.33333 4.69151 8.54221 4.89633 8.88357L6 10.723L7.10367 8.88357C7.30849 8.5422 7.6774 8.33333 8.07549 8.33333H8.8C10.015 8.33333 11 7.34836 11 6.13333V3.2C11 1.98497 10.015 1 8.8 1ZM3.2 0C1.43269 0 0 1.43269 0 3.2V6.13333C0 7.90065 1.43269 9.33333 3.2 9.33333H3.92451C3.97134 9.33333 4.01474 9.35791 4.03884 9.39807L5.42834 11.7139C5.68727 12.1455 6.31273 12.1455 6.57166 11.7139L7.96116 9.39807C7.98526 9.35791 8.02866 9.33333 8.07549 9.33333H8.8C10.5673 9.33333 12 7.90064 12 6.13333V3.2C12 1.43269 10.5673 0 8.8 0H3.2Z" />
          </svg>
          Ask about this video
        </button>
      </div>

      {chatPanelOpen && (
        <>
          <div
            className="fixed inset-0 bg-brand-charcoal/40 backdrop-blur-sm z-40"
            aria-hidden
            onClick={() => setChatPanelOpen(false)}
          />
          <div className="fixed inset-0 z-50 flex flex-col lg:flex-row pointer-events-none">
            <div
              className="flex-1 min-w-0 flex items-center justify-center p-3 sm:p-6 pointer-events-auto"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex flex-col items-center gap-3 w-full max-w-[560px]">
                <div className="rounded-xl overflow-hidden bg-brand-charcoal shadow-lg w-full shrink-0">
                  <StableVideoPlayer ref={sidebarPlayerRef} src={videoStreamUrl} />
                </div>
                <p className="text-sm text-gray-600 truncate w-full text-center">{videoTitle || `Video ${videoId}`}</p>
              </div>
            </div>
            <div
              className="w-full lg:max-w-lg bg-background border-t lg:border-t-0 lg:border-l border-border shadow-lg flex flex-col shrink-0 pointer-events-auto max-h-[70vh] lg:max-h-none"
              onClick={(e) => e.stopPropagation()}
            >
              <Chatbot
                fixedVideoId={videoId ?? ''}
                onClose={() => setChatPanelOpen(false)}
                onSeekToTime={(seconds) => {
                  const player = sidebarPlayerRef.current ?? playerRef.current
                  player?.seekTo(seconds)
                }}
              />
            </div>
          </div>
        </>
      )}

      <div className="flex flex-col lg:flex-row flex-1 overflow-hidden px-3 sm:px-6 pb-4 sm:pb-6 gap-4 lg:gap-6">

        <div className="flex-1 overflow-y-auto min-w-0 pr-0 lg:pr-2 order-2 lg:order-1">

          <Section title="Video description" color="bg-accent">
            {rawAnalysis?.title ? (
              <>
                <div className="flex flex-wrap items-start justify-between gap-2 mb-2">
                  <h4 className="text-base font-semibold text-gray-700 w-fit max-w-full pr-4">{toTitleCase(videoAnalysis.title)}</h4>
                  <button
                    type="button"
                    onClick={generateAnalysis}
                    disabled={generatingAnalysis}
                    className="text-xs font-medium text-accent hover:underline disabled:opacity-60 shrink-0"
                  >
                    {generatingAnalysis ? 'Regenerating…' : 'Regenerate analysis'}
                  </button>
                </div>
                <p className="text-base text-gray-600 leading-relaxed">{videoAnalysis.description}</p>
              </>
            ) : (
              <>
                <p className="text-base text-gray-600 leading-relaxed mb-3">{videoAnalysis.description}</p>
                <button
                  type="button"
                  onClick={generateAnalysis}
                  disabled={generatingAnalysis}
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-accent text-white text-sm font-medium hover:bg-accent/90 disabled:opacity-60 disabled:cursor-not-allowed"
                >
                  {generatingAnalysis ? (
                    <>
                      <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      Generating…
                    </>
                  ) : (
                    'Generate analysis'
                  )}
                </button>
                {analysisError && (
                  <p className="mt-2 text-sm text-red-600" role="alert">{analysisError}</p>
                )}
              </>
            )}
          </Section>

          {rawAnalysis?.title && (
            <>
              <Section title="Categories" badge={videoAnalysis.categories.length} color="bg-accent">
                <div className="flex flex-wrap gap-2">
                  {videoAnalysis.categories.map((cat) => (
                    <span
                      key={cat}
                      className="inline-flex items-center px-3 py-1.5 rounded-md bg-gray-100 text-sm text-gray-700 font-medium"
                    >
                      {cat}
                    </span>
                  ))}
                </div>
              </Section>

              <Section title="About topic" badge={videoAnalysis.topics.length} color="bg-accent">
                <div className="flex flex-wrap gap-2">
                  {videoAnalysis.topics.map((topic) => (
                    <Tag key={topic} label={topic} />
                  ))}
                </div>
              </Section>

              <Section title="Risk involved" badge={videoAnalysis.risks.length} color="bg-error">
                <div className="flex flex-wrap items-center gap-2 sm:gap-3 mb-4">
                  <RiskLevel level={videoAnalysis.riskLevel} />
                  <span className="text-sm text-gray-500">{videoAnalysis.risks.length} issues identified</span>
                </div>
                <ul className="space-y-2">
                  {videoAnalysis.risks.map((risk, i) => (
                    <li
                      key={i}
                      className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-surface border border-border px-3 sm:px-4 py-3"
                    >
                      <span className="text-sm text-gray-700 flex-1 min-w-0">{risk.label}</span>
                      <div className="flex items-center gap-2 shrink-0">
                        <RiskBadge severity={risk.severity} />
                      </div>
                    </li>
                  ))}
                </ul>
              </Section>
            </>
          )}

          <Section
            title="People"
            badge={people.length + mentionedNames.length}
            color="bg-accent"
          >
            {insightsLoading && !insights ? (
              <p className="text-sm text-gray-500">Loading insights…</p>
            ) : !insights && !generatingInsights ? (
              <div>
                <p className="text-sm text-gray-500 mb-3">People and presence are generated from registered entities (faces) that appear in this video. Generate insights after the video is indexed.</p>
                <button
                  type="button"
                  onClick={generateInsights}
                  disabled={generatingInsights}
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-accent text-white text-sm font-medium hover:bg-accent/90 disabled:opacity-60"
                >
                  {generatingInsights ? (
                    <>
                      <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      Generating insights…
                    </>
                  ) : (
                    'Generate insights'
                  )}
                </button>
                {insightsError && <p className="mt-2 text-sm text-red-600" role="alert">{insightsError}</p>}
              </div>
            ) : (
              <>
                <div className="flex flex-wrap items-center justify-between gap-2 mb-2">
                  <p className="text-xs text-gray-500">
                    Shown people ({people.length})
                  </p>
                  <button
                    type="button"
                    onClick={generateInsights}
                    disabled={generatingInsights}
                    className="text-xs font-medium text-accent hover:underline disabled:opacity-60"
                  >
                    {generatingInsights ? 'Regenerating…' : 'Regenerate insights'}
                  </button>
                </div>
                <div className="flex flex-wrap gap-3 mb-4 p-1 -m-1">
                  {people.map((p) => {
                    const isEditing = editingPersonId === p.id
                    return (
                      <div key={p.id} className="relative group flex flex-col items-center gap-1">
                        <button
                          type="button"
                          onClick={() => setSelectedPerson(p)}
                          className={`relative rounded-full ring-2 ring-offset-2 transition-all duration-200 ${
                            selectedPerson?.id === p.id
                              ? 'ring-accent'
                              : 'ring-transparent hover:ring-gray-300'
                          }`}
                        >
                          <Avatar initials={p.avatar} size="sm" imageBase64={p.face_from_video_base64 ?? undefined} />
                          <span
                            role="button"
                            tabIndex={0}
                            onClick={(e) => { e.stopPropagation(); startEditing(p) }}
                            onKeyDown={(e) => { if (e.key === 'Enter') { e.stopPropagation(); startEditing(p) } }}
                            className="absolute -top-1 -right-1 w-5 h-5 rounded-full bg-surface border border-border shadow-sm flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer"
                            aria-label={`Edit name for ${p.name}`}
                          >
                            <svg className="w-2.5 h-2.5 text-gray-500" viewBox="0 0 12 12" fill="currentColor">
                              <path d="M9.08 0.293a1 1 0 011.414 0l1.213 1.213a1 1 0 010 1.414L4.586 10.04 0 12l1.96-4.586L9.08.293zM2.72 7.866l-1.04 2.434 2.434-1.04 6.453-6.453-1.394-1.394L2.72 7.866z" />
                            </svg>
                          </span>
                        </button>
                        {isEditing ? (
                          <input
                            autoFocus
                            value={editName}
                            onChange={(e) => setEditName(e.target.value)}
                            onBlur={() => commitEdit(p.id)}
                            onKeyDown={(e) => { if (e.key === 'Enter') commitEdit(p.id); if (e.key === 'Escape') setEditingPersonId(null) }}
                            className="w-20 text-[10px] text-center text-text-primary border border-accent rounded px-1 py-0.5 focus:outline-none focus:ring-1 focus:ring-accent bg-surface"
                          />
                        ) : (
                          <span
                            className="text-[10px] text-gray-500 truncate max-w-[64px] cursor-pointer hover:text-gray-700"
                            onClick={() => startEditing(p)}
                            title={`Click to edit: ${p.name}`}
                          >
                            {p.name}
                          </span>
                        )}
                      </div>
                    )
                  })}
                </div>

                <p className="text-xs text-gray-500 mb-2">
                  Mentioned people ({mentionedNames.length})
                </p>
                <div className="flex gap-2 mb-5">
                  {mentionedNames.map((name) => (
                    <Tag key={name} label={name} />
                  ))}
                </div>

                {selectedPerson && (
                  <div className="flex flex-wrap items-center gap-3">
                    <Avatar initials={selectedPerson.avatar} size="md" imageBase64={selectedPerson.face_from_video_base64 ?? undefined} />
                    <div className="flex-1 min-w-0">
                      <p className="text-base font-semibold text-gray-700">{selectedPerson.name}</p>
                      <p className="text-sm text-gray-500">
                        Appears in {selectedPerson.percent}% of video
                      </p>
                    </div>
                    <button
                      type="button"
                      onClick={() => setLinkAnalysisPersonId(selectedPerson.id)}
                      className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border bg-surface text-xs font-medium text-text-secondary hover:border-border-light hover:bg-card transition-colors shrink-0 w-full sm:w-auto"
                    >
                      <svg className="w-3.5 h-3.5" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.5">
                        <circle cx="3" cy="6" r="2" />
                        <circle cx="9" cy="3" r="2" />
                        <circle cx="9" cy="9" r="2" />
                        <line x1="4.8" y1="5.2" x2="7.2" y2="3.8" />
                        <line x1="4.8" y1="6.8" x2="7.2" y2="8.2" />
                      </svg>
                      Link Analysis
                    </button>
                  </div>
                )}
                <TimelineBar segments={timelineSegments} durationSeconds={videoDurationSec} />
              </>
            )}
          </Section>

          <Section
            title="Detected objects"
            badge={objectsList.length}
            color="bg-accent"
          >
            {!insights ? (
              <p className="text-sm text-gray-500">Generate insights to see detected objects with timestamps and frames.</p>
            ) : (
              <>
                <div className="flex flex-wrap gap-2 mb-4">
                  {objectsList.map((obj, i) => (
                    <button key={`${obj.object}-${obj.timestamp}-${i}`} type="button" onClick={() => setActiveObjectIdx(i)}>
                      <Tag label={obj.object} active={i === activeObjectIdx} />
                    </button>
                  ))}
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
                  {objectsList.map((obj, i) => {
                    const ts = obj.timestamp
                    const timeStr = fmtSec(ts)
                    const frameUrl = obj.frame_url ? `${API_BASE}${obj.frame_url}` : null
                    const bbox = obj.bbox
                    return (
                      <div
                        key={`${obj.object}-${ts}-${i}`}
                        className={`rounded-lg border overflow-hidden bg-card ${i === activeObjectIdx ? 'ring-2 ring-accent border-accent' : 'border-border'}`}
                      >
                        <button
                          type="button"
                          className="w-full text-left"
                          onClick={() => {
                            setActiveObjectIdx(i)
                            if (Number.isFinite(ts)) playerRef.current?.seekTo(ts)
                          }}
                        >
                          <div className="aspect-video bg-gray-100 flex items-center justify-center overflow-hidden relative">
                            {frameUrl ? (
                              <>
                                <img src={frameUrl} alt="" className="w-full h-full object-cover" />
                                {bbox && (
                                  <span
                                    className="absolute border-2 border-accent pointer-events-none"
                                    style={{
                                      left: `${bbox.left * 100}%`,
                                      top: `${bbox.top * 100}%`,
                                      width: `${bbox.width * 100}%`,
                                      height: `${bbox.height * 100}%`,
                                    }}
                                    aria-hidden
                                  />
                                )}
                              </>
                            ) : (
                              <span className="text-xs text-gray-400">{timeStr}</span>
                            )}
                          </div>
                          <div className="px-2 py-2 flex items-center justify-between gap-2">
                            <span className="text-sm font-medium text-gray-700 truncate">{obj.object}</span>
                            <span className="text-xs font-mono text-accent shrink-0" title="Go to time">{timeStr}</span>
                          </div>
                        </button>
                      </div>
                    )
                  })}
                </div>
              </>
            )}
          </Section>
        </div>

        <div className="w-full lg:w-[420px] shrink-0 flex flex-col gap-3 overflow-hidden order-1 lg:order-2 min-h-0">
          {/* Off-screen video + canvas for clip thumbnails (only when arrived from search) */}
          {hasSearchContext && searchClips.length > 0 && videoStreamUrl && (
            <div className="fixed -left-[9999px] w-px h-px overflow-hidden" aria-hidden>
              <video ref={thumbnailVideoRef} muted playsInline preload="metadata" crossOrigin="anonymous" />
              <canvas ref={thumbnailCanvasRef} />
            </div>
          )}

          <div className="rounded-xl overflow-hidden bg-brand-charcoal shadow-lg shrink-0">
            <StableVideoPlayer ref={playerRef} src={videoStreamUrl} />
          </div>

          <div className="flex flex-wrap items-center justify-between gap-2 shrink-0">
            <div className="flex items-center gap-2 min-w-0">
              <RiskLevel level={videoAnalysis.riskLevel} />

              <div className="relative group ml-1">
                <button
                  type="button"
                  className="p-1 rounded-md text-gray-400 hover:text-gray-700 hover:bg-gray-100 transition-colors duration-200"
                  aria-label="Video details"
                >
                  <svg className="w-4 h-4" viewBox="0 0 12 12" fill="currentColor">
                    <path d="M6.66699 9.33301H5.33301V5.33301H6.66699V9.33301Z" />
                    <path d="M6.66699 4H5.33301V2.66699H6.66699V4Z" />
                    <path fillRule="evenodd" clipRule="evenodd" d="M8.40039 0C10.3883 0.000211285 11.9998 1.61169 12 3.59961V8.40039C11.9998 10.3883 10.3883 11.9998 8.40039 12H3.59961C1.61169 11.9998 0.000211285 10.3883 0 8.40039V3.59961C0.000211156 1.61169 1.61169 0.000211157 3.59961 0H8.40039ZM3.59961 1C2.16398 1.00021 1.00021 2.16398 1 3.59961V8.40039C1.00021 9.83602 2.16398 10.9998 3.59961 11H8.40039C9.83602 10.9998 10.9998 9.83602 11 8.40039V3.59961C10.9998 2.16398 9.83602 1.00021 8.40039 1H3.59961Z" />
                  </svg>
                </button>

                <div className="absolute left-1/2 -translate-x-1/2 top-full mt-2 w-64 rounded-lg border border-gray-300 bg-surface p-4 shadow-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200 z-50">
                  <h4 className="text-base font-semibold text-gray-700 mb-2">Video details</h4>
                  <dl className="space-y-2 text-xs">
                    <div className="flex justify-between">
                      <dt className="text-gray-500">Video ID</dt>
                      <dd className="text-gray-700 font-mono">{videoId}</dd>
                    </div>
                    <div className="flex justify-between">
                      <dt className="text-gray-500">Duration</dt>
                      <dd className="text-gray-700">4:32</dd>
                    </div>
                    <div className="flex justify-between">
                      <dt className="text-gray-500">Resolution</dt>
                      <dd className="text-gray-700">1920 &times; 1080</dd>
                    </div>
                  </dl>
                  <div className="absolute left-1/2 -translate-x-1/2 -top-1.5 w-3 h-3 bg-surface border-l border-t border-gray-300 rotate-45" />
                </div>
              </div>
            </div>

            <div className="flex items-center gap-1.5 shrink-0">
              <Button variant="black" size="small" onClick={() => setReportModalOpen(true)} className="whitespace-nowrap">PDF Report</Button>
            </div>
          </div>
          <PdfReportModal
            open={reportModalOpen}
            onClose={() => setReportModalOpen(false)}
            videoId={videoId ?? ''}
            title={toTitleCase(videoAnalysis.title)}
            riskLevel={videoAnalysis.riskLevel}
            risks={videoAnalysis.risks}
          />

          {hasSearchContext && searchClips.length > 0 && (() => {
            const maxScore = Math.max(...searchClips.map(c => c.score))
            const timelineEnd = searchClips.reduce((mx, c) => Math.max(mx, c.end), 0) * 1.15
            const rel = clipRelevance(searchClips)

            function scoreBarColor(score: number): string {
              if (score >= 0.10) return 'bg-emerald-500'
              if (score >= 0.08) return 'bg-green-500'
              if (score >= 0.06) return 'bg-amber-500'
              return 'bg-red-400'
            }

            return (
              <div className="rounded-xl overflow-hidden shadow-sm border border-gray-200 shrink-0">
                {/* Dark header */}
                <div className="bg-brand-charcoal px-4 py-3.5">
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex items-center gap-3 min-w-0">
                      <div className="w-8 h-8 rounded-lg bg-white/[0.08] flex items-center justify-center shrink-0">
                        <svg className="w-4 h-4 text-gray-300" viewBox="0 0 16 16" fill="none" aria-hidden>
                          <circle cx="7" cy="7" r="5" stroke="currentColor" strokeWidth="1.5"/>
                          <line x1="11" y1="11" x2="14" y2="14" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
                        </svg>
                      </div>
                      <div className="min-w-0">
                        <p className="text-[13px] font-semibold text-white leading-tight truncate">
                          &ldquo;{searchQuery}&rdquo;
                        </p>
                        <p className="text-[11px] text-gray-400 mt-0.5">
                          {searchClips.length} clip{searchClips.length !== 1 ? 's' : ''} found
                        </p>
                      </div>
                    </div>
                    {rel.label && (
                      <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-semibold shrink-0 ${
                        rel.label === 'Highest' ? 'bg-emerald-500/15 text-emerald-400' :
                        rel.label === 'High' ? 'bg-green-500/15 text-green-400' :
                        rel.label === 'Medium' ? 'bg-amber-500/15 text-amber-400' :
                        'bg-red-500/15 text-red-400'
                      }`}>
                        <span className={`w-1.5 h-1.5 rounded-full ${
                          rel.label === 'Highest' ? 'bg-emerald-400' :
                          rel.label === 'High' ? 'bg-green-400' :
                          rel.label === 'Medium' ? 'bg-amber-400' : 'bg-red-400'
                        }`} />
                        {rel.label}
                      </span>
                    )}
                  </div>
                </div>

                {/* Clip results — thumbnail showcase */}
                <div className="bg-surface divide-y divide-gray-100 max-h-[280px] overflow-y-auto">
                  {searchClips.map((clip, i) => {
                    const isActive = activeClipIdx === i
                    const barPct = maxScore > 0 ? (clip.score / maxScore) * 100 : 0

                    return (
                      <button
                        key={i}
                        type="button"
                        onClick={() => {
                          playerRef.current?.seekTo(clip.start)
                          setActiveClipIdx(i)
                        }}
                        className={`w-full flex items-center gap-3 px-4 py-3 transition-all duration-150 group text-left ${
                          isActive
                            ? 'bg-accent/[0.06] border-l-[3px] border-l-accent'
                            : 'border-l-[3px] border-l-transparent hover:bg-gray-50'
                        }`}
                      >
                        {/* Clip thumbnail */}
                        <div className={`w-14 h-10 rounded-md overflow-hidden shrink-0 bg-gray-200 flex items-center justify-center border transition-all duration-150 ${
                          isActive ? 'ring-2 ring-accent border-accent' : 'border-gray-200 group-hover:border-gray-300'
                        }`}>
                          {clipThumbnails[i] ? (
                            <img
                              src={clipThumbnails[i]}
                              alt=""
                              className="w-full h-full object-cover"
                            />
                          ) : (
                            <svg className="w-5 h-5 text-gray-400" viewBox="0 0 12 12" fill="currentColor" aria-hidden>
                              <path d="M3 1.5v9l7.5-4.5L3 1.5z" />
                            </svg>
                          )}
                        </div>

                        {/* Rank + time */}
                        <div className="flex-1 min-w-0 flex items-baseline gap-2">
                          <span className={`text-[11px] font-bold tabular-nums shrink-0 ${
                            isActive ? 'text-accent' : 'text-gray-400'
                          }`}>
                            {i + 1}
                          </span>
                          <span className={`text-sm font-semibold tabular-nums ${
                            isActive ? 'text-accent' : 'text-gray-800'
                          }`}>
                            {fmtSec(clip.start)}<span className="text-gray-400 mx-1">–</span>{fmtSec(clip.end)}
                          </span>
                          <span className="text-[10px] font-medium uppercase tracking-wider text-gray-400 shrink-0">
                            {clip.type}
                          </span>
                        </div>

                        {/* Score bar + percentage */}
                        <div className="w-[88px] shrink-0 flex items-center gap-2">
                          <div className="flex-1 h-[5px] rounded-full bg-gray-100 overflow-hidden">
                            <div
                              className={`h-full rounded-full transition-all duration-300 ${scoreBarColor(clip.score)}`}
                              style={{ width: `${barPct}%` }}
                            />
                          </div>
                          <span className={`text-[11px] font-bold tabular-nums w-[38px] text-right ${
                            isActive ? 'text-accent' : clipScoreColor(clip.score)
                          }`}>
                            {(clip.score * 100).toFixed(1)}%
                          </span>
                        </div>
                      </button>
                    )
                  })}
                </div>

                {/* Timeline bar */}
                {timelineEnd > 0 && (
                  <div className="px-4 py-3 bg-gray-50/80 border-t border-gray-100">
                    <p className="text-[10px] font-medium text-gray-400 uppercase tracking-wider mb-2">
                      Clip positions
                    </p>
                    <div className="relative h-[6px] rounded-full bg-gray-200 overflow-visible">
                      {searchClips.map((clip, i) => {
                        const leftPct = (clip.start / timelineEnd) * 100
                        const widthPct = Math.max(((clip.end - clip.start) / timelineEnd) * 100, 1.2)
                        const isActive2 = activeClipIdx === i
                        return (
                          <button
                            key={i}
                            type="button"
                            onClick={() => {
                              playerRef.current?.seekTo(clip.start)
                              setActiveClipIdx(i)
                            }}
                            className={`absolute top-0 h-full rounded-sm cursor-pointer transition-all duration-150 ${
                              isActive2 ? 'ring-2 ring-accent/40 scale-y-[1.6] z-10' : 'hover:scale-y-[1.4] z-0'
                            } ${scoreBarColor(clip.score)}`}
                            style={{ left: `${leftPct}%`, width: `${widthPct}%` }}
                            title={`${fmtSec(clip.start)} – ${fmtSec(clip.end)}`}
                          />
                        )
                      })}
                    </div>
                    <div className="flex justify-between mt-1.5">
                      <span className="text-[10px] text-gray-400 tabular-nums">0:00</span>
                      <span className="text-[10px] text-gray-400 tabular-nums">{fmtSec(timelineEnd)}</span>
                    </div>
                  </div>
                )}
              </div>
            )
          })()}

          <div className="rounded-lg border border-gray-300 bg-surface shadow-sm overflow-hidden flex flex-col min-h-0 shrink-0">
            <div className="flex items-center justify-between px-3 sm:px-4 py-3 border-b border-border shrink-0">
              <div className="flex items-center gap-2">
                <svg className="w-4 h-4 text-gray-500" viewBox="0 0 12 11" fill="currentColor">
                  <path d="M1 1H11V2H1V1Z" />
                  <path d="M1 4H9V5H1V4Z" />
                  <path d="M1 7H11V8H1V7Z" />
                  <path d="M1 10H7V11H1V10Z" />
                </svg>
                <h4 className="text-base font-semibold text-gray-700">Transcript</h4>
              </div>
              <span className="text-xs text-gray-400">{videoAnalysis.transcript.length} segments</span>
            </div>
            <ul className="overflow-y-auto divide-y divide-gray-100">
              {(() => {
                const segments = videoAnalysis.transcript
                const visible = (isLgViewport || showAllTranscript) ? segments : segments.slice(0, 2)
                return visible.map((line, i) => (
                  <li
                    key={i}
                    className="flex gap-3 px-3 sm:px-4 py-3 hover:bg-card transition-colors duration-150 cursor-pointer"
                  >
                    <span className="text-xs font-mono text-accent font-medium shrink-0 pt-0.5 w-9">
                      {line.time}
                    </span>
                    <p className="text-sm text-gray-600 leading-relaxed">{line.text}</p>
                  </li>
                ))
              })()}
            </ul>
            {videoAnalysis.transcript.length > 2 && !isLgViewport && (
              <div className="shrink-0 border-t border-gray-100 px-3 sm:px-4 py-3 flex justify-center">
                <button
                  type="button"
                  onClick={() => setShowAllTranscript((v) => !v)}
                  className="inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium text-accent hover:bg-accent/5 transition-colors"
                >
                  {showAllTranscript ? (
                    <>
                      <svg className="w-4 h-4 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden>
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
                      </svg>
                      Show less
                    </>
                  ) : (
                    <>
                      <svg className="w-4 h-4 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden>
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                      </svg>
                      Show more ({videoAnalysis.transcript.length - 2} more)
                    </>
                  )}
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
      {linkAnalysisPersonId !== null && linkDataByEntity[linkAnalysisPersonId] && (() => {
        const linkData = linkDataByEntity[linkAnalysisPersonId]
        const person = people.find((p) => p.id === linkAnalysisPersonId)
        const personFaceBase64 = linkData.personFaceBase64 ?? person?.face_from_video_base64
        return (
          <LinkAnalysisModal
            open
            onClose={() => setLinkAnalysisPersonId(null)}
            data={{ ...linkData, personFaceBase64 }}
            onSeekToTime={(seconds) => playerRef.current?.seekTo(seconds)}
          />
        )
      })()}
    </div>
  )
}
