import { useState, useEffect, useRef, useCallback, forwardRef, useImperativeHandle } from 'react'
import { useParams, useLocation, Link } from 'react-router-dom'
import { jsPDF } from 'jspdf'
import LinkAnalysisModal, { type PersonLinkData } from '../components/LinkAnalysisModal'
import Chatbot from './Chatbot'
import { useVideoCache } from '../contexts/VideoCache'
/* Strand: design system icons */
import documentListIconUrl from '../../strand/icons/document-list.svg?url'
import generateIconUrl from '../../strand/icons/generate.svg?url'
import exclamationIconUrl from '../../strand/icons/exclamation.svg?url'
import entityIconUrl from '../../strand/icons/entity.svg?url'
import visionIconUrl from '../../strand/icons/vision.svg?url'
import transcriptionIconUrl from '../../strand/icons/transcription.svg?url'
import checkmarkIconUrl from '../../strand/icons/checkmark.svg?url'
import spinnerIconUrl from '../../strand/icons/spinner.svg?url'

import { API_BASE } from '../config'

function toTitleCase(s: string): string {
  return s.replace(/\b\w/g, (c) => c.toUpperCase())
}

/** Analysis generated by API and stored in video metadata (video_analysis). */
type VideoAnalysisData = {
  title: string
  description: string
  categories: string[]
  topics: string[]
  people: string[]
  riskLevel: 'high' | 'medium' | 'low'
  risks: Array<{ label: string; severity: 'high' | 'medium' | 'low'; timestamp?: string | null }>
  transcript: Array<{ time: string; text: string }>
}

const DEFAULT_VIDEO_PLACEHOLDER: VideoAnalysisData = {
  title: '—',
  description: '',
  categories: [],
  topics: [],
  people: [],
  riskLevel: 'medium',
  risks: [],
  transcript: [],
}

/** Sections that will appear after analysis — empty state: card uses accent, icon box gets the product/accent tint */
const ANALYSIS_SECTIONS = [
  { id: 'description', label: 'Video description', desc: 'Summary and context', iconUrl: documentListIconUrl, iconBg: 'bg-[var(--strand-ui-accent-light)]' },
  { id: 'categories', label: 'Categories & topics', desc: 'Themes and subject tags', iconUrl: generateIconUrl, iconBg: 'bg-[var(--strand-product-generate-light)]' },
  { id: 'risks', label: 'Risk involved', desc: 'Issues and severity', iconUrl: exclamationIconUrl, iconBg: 'bg-[var(--strand-product-search-light)]' },
  { id: 'people', label: 'People', desc: 'Faces and names', iconUrl: entityIconUrl, iconBg: 'bg-[var(--strand-ui-accent-light)]' },
  { id: 'objects', label: 'Detected objects', desc: 'Items with timestamps', iconUrl: visionIconUrl, iconBg: 'bg-[var(--strand-product-embed-light)]' },
  { id: 'transcript', label: 'Transcript', desc: 'Speech with times', iconUrl: transcriptionIconUrl, iconBg: 'bg-[var(--strand-product-generate-light)]' },
] as const

/** From API: /api/videos/:id/insights */
type PersonInsight = {
  entity_id: string
  name: string
  avatar: string
  percent: number
  face_snap_base64?: string | null
  face_from_video_base64?: string | null
  clips: Array<{ start: number; end: number; score: number }>
}
/** Detected face from keyframes (no entity matching) */
type DetectedFace = {
  face_id: number
  confidence: number
  image_base64: string
  bbox?: { x: number; y: number; w: number; h: number }
  timestamps: number[]
  appearance_count: number
}
type ObjectInsight = {
  object: string
  timestamp: number
  frame_url?: string
  bbox?: { left: number; top: number; width: number; height: number }
}
type VideoInsights = {
  people?: PersonInsight[]
  mentioned?: string[]
  detected_faces?: DetectedFace[]
  objects: ObjectInsight[]
  link_data_by_entity?: Record<string, PersonLinkData>
  video_duration_sec: number
}


function Button({
  children,
  variant = 'black',
  size = 'regular',
  onClick,
  className = '',
}: {
  children: React.ReactNode
  variant?: 'black' | 'white' | 'gray' | 'ghosted-black' | 'black-outline'
  size?: 'small' | 'regular' | 'medium'
  onClick?: () => void
  className?: string
}) {
  const sizeMap = {
    small: 'h-7 px-2 py-1.5 text-sm rounded-md gap-1',
    regular: 'h-8 px-3 py-1.5 text-base rounded-[9.6px] gap-1',
    medium: 'h-10 px-[18px] py-2 text-lg rounded-lg gap-1',
  }
  const variantMap = {
    black:
      'bg-brand-charcoal text-brand-white hover:bg-gray-300 hover:text-brand-charcoal',
    white:
      'bg-surface text-brand-charcoal hover:bg-gray-300 hover:text-brand-charcoal',
    gray:
      'bg-gray-200 text-brand-charcoal hover:bg-gray-400 hover:text-brand-charcoal',
    'ghosted-black':
      'bg-transparent text-brand-charcoal hover:bg-brand-charcoal/[0.08]',
    'black-outline':
      'bg-transparent text-brand-charcoal border border-brand-charcoal hover:bg-gray-300',
  }

  return (
    <button
      type="button"
      onClick={onClick}
      className={`inline-flex items-center justify-center font-brand transition-all duration-200 ${sizeMap[size]} ${variantMap[variant]} ${className}`}
    >
      {children}
    </button>
  )
}

const SECTION_UNDERLINE_MAP: Record<string, string> = {
  'bg-accent': 'border-accent',
  'bg-product-generate': 'border-product-generate',
  'bg-product-embed': 'border-product-embed',
  'bg-product-search': 'border-product-search',
  'bg-error': 'border-error',
}

function Section({
  title,
  badge,
  color,
  children,
}: {
  title: string
  badge?: number
  color: string
  children: React.ReactNode
}) {
  const badgeBgMap: Record<string, string> = {
    'bg-accent': 'bg-accent/10 text-accent',
    'bg-product-generate': 'bg-product-generate/10 text-product-generate',
    'bg-product-embed': 'bg-product-embed/10 text-product-embed',
    'bg-product-search': 'bg-product-search/10 text-product-search',
    'bg-error': 'bg-error/10 text-error',
  }
  const badgeStyle = badgeBgMap[color] ?? 'bg-gray-100 text-gray-500'
  const underlineStyle = SECTION_UNDERLINE_MAP[color] ?? 'border-gray-300'

  return (
    <div className="py-3 sm:py-4">
      <div className={`w-fit border-b-2 pb-1.5 ${underlineStyle}`}>
        <div className="flex items-center gap-2">
          <h3 className="text-base font-semibold text-text-primary">{title}</h3>
          {badge !== undefined && (
            <span className={`text-[11px] font-medium px-1.5 py-0.5 rounded-full ${badgeStyle}`}>{badge}</span>
          )}
        </div>
      </div>
      <div className="mt-3">{children}</div>
    </div>
  )
}

function Avatar({ initials, size = 'md', imageBase64 }: { initials: string; size?: 'sm' | 'md'; imageBase64?: string | null }) {
  const dim = size === 'sm' ? 'w-9 h-9 text-xs' : 'w-12 h-12 text-sm'
  if (imageBase64) {
    return (
      <div className={`${dim} rounded-full overflow-hidden bg-gray-200 shrink-0 ring-1 ring-gray-300`}>
        <img src={`data:image/png;base64,${imageBase64}`} alt="" className="w-full h-full object-cover" />
      </div>
    )
  }
  return (
    <div className={`${dim} rounded-full bg-gray-300 text-gray-600 font-medium flex items-center justify-center shrink-0`}>
      {initials}
    </div>
  )
}

function Tag({ label, active = false }: { label: string; active?: boolean }) {
  return (
    <span
      className={`inline-block px-3 py-1 rounded-full text-sm border cursor-pointer transition-colors duration-200 ${
        active
          ? 'bg-brand-charcoal text-brand-white border-brand-charcoal'
          : 'bg-surface text-gray-700 border-gray-300 hover:border-gray-400'
      }`}
    >
      {label}
    </span>
  )
}

function RiskBadge({ severity }: { severity: 'high' | 'medium' | 'low' }) {
  const styles = {
    high: 'bg-error/10 text-error border-error/20',
    medium: 'bg-warning/10 text-warning border-warning/20',
    low: 'bg-success/10 text-success border-success/20',
  }
  return (
    <span className={`inline-flex items-center px-2 py-0.5 rounded-sm text-xs font-medium border ${styles[severity]}`}>
      {severity.charAt(0).toUpperCase() + severity.slice(1)}
    </span>
  )
}

/* Overall risk indicator                                              */
function RiskLevel({ level }: { level: 'high' | 'medium' | 'low' }) {
  const config = {
    high: { label: 'High Risk', bg: 'bg-error/10', text: 'text-error', dot: 'bg-error' },
    medium: { label: 'Medium Risk', bg: 'bg-warning/10', text: 'text-warning', dot: 'bg-warning' },
    low: { label: 'Low Risk', bg: 'bg-success/10', text: 'text-success', dot: 'bg-success' },
  }
  const c = config[level]
  return (
    <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-sm font-medium ${c.bg} ${c.text}`}>
      <span className={`w-2 h-2 rounded-full ${c.dot}`} />
      {c.label}
    </span>
  )
}

function formatTimelineTime(totalSeconds: number): string {
  const m = Math.floor(totalSeconds / 60)
  const s = Math.floor(totalSeconds % 60)
  return `${m}:${s.toString().padStart(2, '0')}`
}

function TimelineBar({
  segments,
  durationSeconds,
}: {
  segments: number[]
  durationSeconds?: number
}) {
  const n = segments.length
  const duration = durationSeconds ?? (n * 13)
  const segmentDuration = duration / n
  const showMidTick = duration > 90
  const midTime = showMidTick ? Math.round((duration / 2) / 30) * 30 : 0

  return (
    <div className="mt-3 w-full">
      <p className="mb-1.5 text-xs font-medium text-gray-500">Presence in video</p>
      <div className="flex gap-0.5 w-full h-2.5 rounded-sm overflow-hidden bg-gray-100">
        {segments.map((filled, i) => (
          <div
            key={i}
            className={`flex-1 min-w-0 rounded-sm ${filled ? 'timeline-embed-gradient' : 'bg-gray-200'}`}
            style={
              filled
                ? {
                    backgroundSize: `${n * 100}% 100%`,
                    backgroundPosition: `${(-i * 100) / (n || 1)}% 0`,
                  }
                : undefined
            }
            title={`${formatTimelineTime(i * segmentDuration)} – ${formatTimelineTime((i + 1) * segmentDuration)}`}
          />
        ))}
      </div>
      <div
        className={`mt-1 w-full text-[11px] text-gray-500 tabular-nums ${showMidTick ? 'grid grid-cols-3 items-center' : 'flex justify-between'}`}
        aria-hidden
      >
        <span>0:00</span>
        {showMidTick ? <span className="text-center">{formatTimelineTime(midTime)}</span> : null}
        <span className={showMidTick ? 'text-right' : ''}>{formatTimelineTime(duration)}</span>
      </div>
    </div>
  )
}

function fmtSecPdf(seconds: number): string {
  if (!Number.isFinite(seconds) || seconds < 0) return '—'
  const m = Math.floor(seconds / 60)
  const s = Math.floor(seconds % 60)
  return `${m}:${s.toString().padStart(2, '0')}`
}

function PdfReportModal({
  open,
  onClose,
  videoId,
  videoAnalysis,
  detectedFaces = [],
  objects = [],
}: {
  open: boolean
  onClose: () => void
  videoId: string
  videoAnalysis: VideoAnalysisData
  detectedFaces?: DetectedFace[]
  objects?: ObjectInsight[]
}) {
  if (!open) return null

  const { title, description, categories, topics, riskLevel, risks, transcript } = videoAnalysis
  const objectsCount = objects.length
  const detectedFacesCount = detectedFaces.length

  async function handleDownload() {
    const doc = new jsPDF({ format: 'a4', unit: 'mm' })
    const margin = 18
    const footerH = 12
    const pageW = doc.internal.pageSize.getWidth()
    const pageH = doc.internal.pageSize.getHeight()
    const contentH = pageH - margin - footerH
    const maxW = pageW - margin * 2
    let y = margin
    let sectionNum = 0
    const lineHeight = 5.5
    const sectionGap = 12
    const headingUnderline = 0.3

    function checkPage(need: number = 24) {
      if (y + need > contentH) {
        doc.addPage()
        y = margin
      }
    }

    function addFooter(pageNum: number, totalPages: number) {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(120, 120, 120)
      const footerY = pageH - 6
      doc.text(
        `Compliance Intelligence Report  ·  ${title || 'Video'}  ·  Page ${pageNum} of ${totalPages}`,
        margin,
        footerY
      )
      doc.text(
        new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' }),
        pageW - margin,
        footerY,
        { align: 'right' }
      )
      doc.setTextColor(0, 0, 0)
    }

    function addSectionHeading(text: string, fontSize: number = 12) {
      sectionNum += 1
      checkPage(16)
      doc.setDrawColor(60, 60, 60)
      doc.setLineWidth(headingUnderline)
      doc.line(margin, y - 2, margin + 40, y - 2)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(100, 100, 100)
      doc.text(`Section ${sectionNum}`, margin, y)
      doc.setTextColor(0, 0, 0)
      y += 5
      doc.setFontSize(fontSize)
      doc.setFont('helvetica', 'bold')
      doc.text(text, margin, y)
      y += lineHeight + 4
    }

    function addBody(text: string, fontSize: number = 10) {
      doc.setFontSize(fontSize)
      doc.setFont('helvetica', 'normal')
      const lines = doc.splitTextToSize(text, maxW)
      for (const line of lines) {
        checkPage(lineHeight)
        doc.text(line, margin, y)
        y += lineHeight
      }
      y += 4
    }

    // —— Cover page ——
    doc.setFillColor(40, 40, 40)
    doc.rect(0, 0, pageW, 32, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    doc.text('Compliance Intelligence Report', margin, 20)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')
    doc.text('Video analysis, risk assessment & transcript', margin, 28)
    doc.setTextColor(0, 0, 0)

    y = 50
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text(title || 'Video Analysis', margin, y)
    y += lineHeight + 2
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(80, 80, 80)
    doc.text(`Video ID: ${videoId}`, margin, y)
    y += lineHeight
    doc.text(`Generated: ${new Date().toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })}`, margin, y)
    doc.setTextColor(0, 0, 0)
    y = pageH - footerH - 10
    doc.setDrawColor(200, 200, 200)
    doc.setLineWidth(0.5)
    doc.line(margin, y, pageW - margin, y)
    doc.addPage()
    y = margin

    // —— Executive summary ——
    addSectionHeading('Executive summary', 11)
    const riskColor = riskLevel === 'high' ? [180, 60, 60] : riskLevel === 'medium' ? [180, 120, 40] : [60, 120, 80]
    doc.setFillColor(riskColor[0], riskColor[1], riskColor[2])
    doc.roundedRect(margin, y, 14, 8, 1.5, 1.5, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.text((riskLevel || '—').toUpperCase(), margin + 3, y + 5.5)
    doc.setTextColor(0, 0, 0)
    doc.setFont('helvetica', 'normal')
    doc.text('  Risk level', margin + 17, y + 5.5)
    y += 12
    doc.setFontSize(10)
    addBody(
      [
        `This report covers analysis of the video "${(title || 'Video').slice(0, 50)}${(title || '').length > 50 ? '…' : ''}". `,
        `Categories: ${categories?.length ?? 0}. Topics: ${topics?.length ?? 0}. `,
        `Key findings: ${risks?.length ?? 0} risk(s). `,
        detectedFacesCount > 0 || objectsCount > 0
          ? `Insights: ${detectedFacesCount} face(s), ${objectsCount} object(s) detected. `
          : '',
        transcript?.length ? `Full transcript: ${transcript.length} segment(s).` : '',
      ].join('')
    )
    y += sectionGap

    // —— Description ——
    addSectionHeading('Description')
    addBody(description || 'No description available.')

    // —— Categories & topics ——
    if (categories?.length) {
      addSectionHeading('Categories')
      addBody(categories.join('  ·  '))
    }
    if (topics?.length) {
      addSectionHeading('Topics')
      addBody(topics.join('  ·  '))
    }

    // —— Risk assessment ——
    addSectionHeading('Risk assessment')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text(`Level: ${(riskLevel || '—').toUpperCase()}`, margin, y)
    y += lineHeight + 6

    if (risks?.length) {
      doc.setFontSize(10)
      doc.setFont('helvetica', 'bold')
      doc.text('Key findings', margin, y)
      y += lineHeight + 3
      for (const r of risks) {
        checkPage(lineHeight * 2)
        const severityColor = r.severity === 'high' ? [180, 60, 60] : r.severity === 'medium' ? [180, 120, 40] : [80, 120, 80]
        doc.setFillColor(severityColor[0], severityColor[1], severityColor[2])
        doc.roundedRect(margin, y - 3.5, 3, 3, 0.5, 0.5, 'F')
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(10)
        const labelLines = doc.splitTextToSize(r.label || '', maxW - 28)
        for (let i = 0; i < labelLines.length; i++) {
          doc.text(labelLines[i], margin + 6, y)
          if (i === 0) doc.text(String(r.severity || '').toUpperCase(), pageW - margin - 18, y)
          y += lineHeight
        }
        if (r.timestamp) {
          doc.setFontSize(9)
          doc.setTextColor(100, 100, 100)
          doc.text(`Time: ${r.timestamp}`, margin + 6, y)
          doc.setTextColor(0, 0, 0)
          y += lineHeight
        }
        y += 4
      }
      y += 4
    }

    // —— Detected faces ——
    if (detectedFacesCount > 0) {
      addSectionHeading('Detected faces')
      addBody(`${detectedFacesCount} unique face(s) detected from keyframes.`)
      const imgSize = 22
      const imgGap = 4
      for (let i = 0; i < detectedFaces.length; i++) {
        const face = detectedFaces[i]
        checkPage(imgSize + 20)
        try {
          if (face.image_base64) {
            doc.setDrawColor(220, 220, 220)
            doc.setLineWidth(0.3)
            doc.rect(margin, y, imgSize, imgSize)
            doc.addImage(face.image_base64, 'PNG', margin, y, imgSize, imgSize)
          }
        } catch {
          /* skip image if invalid */
        }
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(10)
        doc.text(`Face ${i + 1}`, margin + imgSize + imgGap, y + 5)
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(9)
        doc.text(`Confidence: ${Math.round(face.confidence * 100)}%  ·  Appearances: ${face.appearance_count}`, margin + imgSize + imgGap, y + 11)
        const tsStr = face.timestamps?.length ? face.timestamps.map(fmtSecPdf).join(', ') : '—'
        doc.text(`Timestamps: ${tsStr}`, margin + imgSize + imgGap, y + 17)
        y += imgSize + imgGap + 6
      }
      y += sectionGap
    }

    // —— Detected objects ——
    if (objectsCount > 0) {
      addSectionHeading('Detected objects')
      addBody(`${objectsCount} object(s) detected with timestamps.`)
      const objectImages = await Promise.all(
        objects.map(async (obj) => {
          if (!obj.frame_url) return null
          try {
            const res = await fetch(`${API_BASE}${obj.frame_url}`)
            if (!res.ok) return null
            const blob = await res.blob()
            return new Promise<string>((resolve, reject) => {
              const r = new FileReader()
              r.onload = () => resolve(r.result as string)
              r.onerror = reject
              r.readAsDataURL(blob)
            })
          } catch {
            return null
          }
        })
      )
      const objImgSize = 28
      const objImgGap = 6
      for (let i = 0; i < objects.length; i++) {
        const obj = objects[i]
        checkPage(objImgSize + 14)
        const dataUrl = objectImages[i]
        if (dataUrl) {
          try {
            doc.setDrawColor(220, 220, 220)
            doc.setLineWidth(0.2)
            doc.rect(margin, y, objImgSize, objImgSize * 0.75)
            doc.addImage(dataUrl, 'JPEG', margin, y, objImgSize, objImgSize * 0.75)
          } catch {
            /* skip */
          }
        }
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(10)
        doc.text(obj.object || 'Object', margin + (dataUrl ? objImgSize + objImgGap : 0), y + 5)
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(9)
        doc.text(`Timestamp: ${fmtSecPdf(obj.timestamp)}`, margin + (dataUrl ? objImgSize + objImgGap : 0), y + 12)
        const rowH = dataUrl ? objImgSize * 0.75 + objImgGap : lineHeight * 2 + 2
        y += rowH + 6
      }
      y += sectionGap
    }

    // —— Transcript ——
    addSectionHeading('Transcript')
    if (transcript?.length) {
      doc.setFontSize(9)
      doc.setTextColor(80, 80, 80)
      doc.text(`${transcript.length} segment(s)`, margin, y)
      doc.setTextColor(0, 0, 0)
      y += lineHeight + 4
      for (let idx = 0; idx < transcript.length; idx++) {
        const seg = transcript[idx]
        checkPage(lineHeight * 3)
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(9)
        doc.text(seg.time || '0:00', margin, y)
        doc.setFont('helvetica', 'normal')
        const textLines = doc.splitTextToSize(seg.text || '', maxW - 14)
        doc.text(textLines[0], margin + 14, y)
        y += lineHeight
        for (let i = 1; i < textLines.length; i++) {
          checkPage(lineHeight)
          doc.text(textLines[i], margin + 14, y)
          y += lineHeight
        }
        y += 4
      }
    } else {
      addBody('No transcript available. Generate transcript from the Transcript section.')
    }

    // Add footers to all pages
    const totalPages = doc.getNumberOfPages()
    for (let p = 1; p <= totalPages; p++) {
      doc.setPage(p)
      addFooter(p, totalPages)
    }

    doc.save(`compliance-report-${videoId}.pdf`)
  }

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center p-3 sm:p-4">
      <div className="absolute inset-0 bg-brand-charcoal/40 backdrop-blur-sm" onClick={onClose} aria-hidden />
      <div
        className="relative w-full max-w-2xl max-h-[90vh] flex flex-col rounded-xl border border-border bg-surface shadow-xl"
        role="dialog"
        aria-modal="true"
        aria-labelledby="pdf-report-title"
      >
        <div className="flex items-center justify-between border-b border-border px-5 py-4 shrink-0">
          <h2 id="pdf-report-title" className="text-lg font-semibold text-text-primary">
            PDF Report
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="p-2 rounded-lg text-text-tertiary hover:bg-card hover:text-text-primary transition-colors"
            aria-label="Close"
          >
            <svg className="w-5 h-5" viewBox="0 0 12 12" fill="currentColor">
              <path d="M6.02051 5.31348L8.9668 2.36719L9.67383 3.07422L6.72754 6.02051L9.65332 8.94629L8.94629 9.65332L6.02051 6.72754L3.07422 9.67383L2.36719 8.9668L5.31348 6.02051L2.34668 3.05371L3.05371 2.34668L6.02051 5.31348Z" />
              <path fillRule="evenodd" clipRule="evenodd" d="M8.40039 0C10.3883 0.000211285 11.9998 1.61169 12 3.59961V8.40039C11.9998 10.3883 10.3883 11.9998 8.40039 12H3.59961C1.61169 11.9998 0.000211285 10.3883 0 8.40039V3.59961C0.000211156 1.61169 1.61169 0.000211157 3.59961 0H8.40039ZM3.59961 1C2.16398 1.00021 1.00021 2.16398 1 3.59961V8.40039C1.00021 9.83602 2.16398 10.9998 3.59961 11H8.40039C9.83602 10.9998 10.9998 9.83602 11 8.40039V3.59961C10.9998 2.16398 9.83602 1.00021 8.40039 1H3.59961Z" />
            </svg>
          </button>
        </div>
        <div className="flex-1 overflow-y-auto p-5 bg-card">
          <div className="bg-surface rounded-lg border border-border shadow-sm p-6 text-text-primary space-y-5">
            <p className="text-xs text-text-tertiary uppercase tracking-wider">Compliance Intelligence Report</p>
            <h3 className="text-lg font-semibold text-text-primary">{toTitleCase(title)}</h3>
            <p className="text-sm text-text-secondary">Video ID: {videoId} · Generated: {new Date().toLocaleDateString()}</p>

            {description && (
              <div className="border-t border-border pt-4">
                <p className="text-xs font-medium text-text-tertiary uppercase mb-2">Description</p>
                <p className="text-sm text-text-secondary whitespace-pre-wrap">{description}</p>
              </div>
            )}

            {categories?.length > 0 && (
              <div className="border-t border-border pt-4">
                <p className="text-xs font-medium text-text-tertiary uppercase mb-2">Categories</p>
                <p className="text-sm text-text-secondary">{categories.join(' · ')}</p>
              </div>
            )}

            {topics?.length > 0 && (
              <div className="border-t border-border pt-4">
                <p className="text-xs font-medium text-text-tertiary uppercase mb-2">Topics</p>
                <p className="text-sm text-text-secondary">{topics.join(' · ')}</p>
              </div>
            )}

            <div className="border-t border-border pt-4">
              <p className="text-xs font-medium text-text-tertiary uppercase mb-2">Risk level</p>
              <p className="text-sm font-medium capitalize">{riskLevel}</p>
            </div>

            {risks?.length > 0 && (
              <div className="border-t border-border pt-4">
                <p className="text-xs font-medium text-gray-500 uppercase mb-2">Key findings</p>
                <ul className="space-y-1.5 text-sm">
                  {risks.map((r, i) => (
                    <li key={i} className="flex justify-between gap-2">
                      <span>{r.label}</span>
                      <span className={`shrink-0 text-xs font-medium capitalize ${r.severity === 'high' ? 'text-error' : r.severity === 'medium' ? 'text-warning' : 'text-success'}`}>{r.severity}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {detectedFacesCount > 0 && (
              <div className="border-t border-border pt-4">
                <p className="text-xs font-medium text-text-tertiary uppercase mb-2">Detected faces ({detectedFacesCount})</p>
                <div className="flex flex-wrap gap-4">
                  {detectedFaces.map((face, i) => (
                    <div key={i} className="flex items-start gap-3">
                      <img src={`data:image/png;base64,${face.image_base64}`} alt="" className="w-14 h-14 rounded-full object-cover border border-border" />
                      <div className="text-sm text-text-secondary">
                        <p className="font-medium text-text-primary">Face {i + 1}</p>
                        <p>Confidence: {Math.round(face.confidence * 100)}% · Appearances: {face.appearance_count}</p>
                        <p className="text-xs text-text-tertiary">Timestamps: {face.timestamps?.length ? face.timestamps.map(fmtSecPdf).join(', ') : '—'}</p>
                      </div>
                    </div>
                  ))}
                </div>
                <p className="text-xs text-text-tertiary mt-2">All face snapshots included in PDF.</p>
              </div>
            )}

            {objectsCount > 0 && (
              <div className="border-t border-border pt-4">
                <p className="text-xs font-medium text-text-tertiary uppercase mb-2">Detected objects ({objectsCount})</p>
                <ul className="space-y-2">
                  {objects.map((obj, i) => (
                    <li key={i} className="flex items-center gap-3 text-sm">
                      {obj.frame_url && (
                        <img src={`${API_BASE}${obj.frame_url}`} alt="" className="w-16 h-12 rounded border border-border object-cover" />
                      )}
                      <span className="font-medium text-text-primary">{obj.object}</span>
                      <span className="text-text-tertiary">at {fmtSecPdf(obj.timestamp)}</span>
                    </li>
                  ))}
                </ul>
                <p className="text-xs text-text-tertiary mt-2">Object snapshots and timestamps included in PDF.</p>
              </div>
            )}

            <div className="border-t border-border pt-4">
              <p className="text-xs font-medium text-text-tertiary uppercase mb-2">Transcript ({transcript?.length ?? 0} segments)</p>
              <div className="max-h-48 overflow-y-auto rounded border border-border bg-card p-3 text-sm">
                {transcript?.length ? (
                  <ul className="space-y-2">
                    {transcript.slice(0, 20).map((seg, i) => (
                      <li key={i}>
                        <span className="text-text-tertiary font-mono text-xs mr-2">{seg.time}</span>
                        <span className="text-text-secondary">{seg.text}</span>
                      </li>
                    ))}
                    {transcript.length > 20 && (
                      <li className="text-text-tertiary text-xs">… and {transcript.length - 20} more (included in PDF)</li>
                    )}
                  </ul>
                ) : (
                  <p className="text-text-tertiary text-sm">No transcript. Generate from the Transcript section.</p>
                )}
              </div>
            </div>
            <p className="text-xs text-text-tertiary">Download for full PDF including face & object snapshots, insights, and complete transcript.</p>
          </div>
        </div>
        <div className="flex flex-wrap items-center justify-end gap-2 border-t border-border px-3 sm:px-5 py-4 shrink-0 bg-surface rounded-b-xl">
          <Button variant="ghosted-black" size="regular" onClick={onClose}>Close</Button>
          <Button variant="black" size="regular" onClick={handleDownload}>Download PDF</Button>
        </div>
      </div>
    </div>
  )
}

type PersonEntry = { id: string; name: string; avatar: string; percent: number; face_snap_base64?: string | null; face_from_video_base64?: string | null; clips: Array<{ start: number; end: number; score: number }> }

type ClipMatch = { start: number; end: number; score: number; type: string }

function fmtSec(seconds: number): string {
  if (!Number.isFinite(seconds) || seconds < 0) return '—'
  const h = Math.floor(seconds / 3600)
  const m = Math.floor((seconds % 3600) / 60)
  const s = Math.floor(seconds % 60)
  if (h > 0) return `${h}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`
  return `${m}:${s.toString().padStart(2, '0')}`
}

/** Parse "M:SS" or "H:MM:SS" to seconds for video seek. */
function parseTimestampToSeconds(timestamp: string): number {
  const s = String(timestamp).trim()
  if (!s) return NaN
  const parts = s.split(':').map((p) => parseInt(p, 10))
  if (parts.some((n) => !Number.isFinite(n) || n < 0)) return NaN
  if (parts.length === 2) return parts[0] * 60 + parts[1]
  if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2]
  if (parts.length === 1) return parts[0]
  return NaN
}

function clipRelevance(clips: ClipMatch[]): { label: string; color: string } {
  if (!clips.length) return { label: '', color: '' }
  const best = Math.max(...clips.map((c) => c.score))
  if (best >= 0.10) return { label: 'Highest', color: 'bg-emerald-100 text-emerald-800 border-emerald-300' }
  if (best >= 0.08) return { label: 'High', color: 'bg-green-100 text-green-800 border-green-300' }
  if (best >= 0.06) return { label: 'Medium', color: 'bg-yellow-100 text-yellow-800 border-yellow-300' }
  return { label: 'Low', color: 'bg-red-50 text-red-700 border-red-200' }
}

function clipScoreColor(score: number): string {
  if (score >= 0.10) return 'text-emerald-700'
  if (score >= 0.08) return 'text-green-700'
  if (score >= 0.06) return 'text-yellow-700'
  return 'text-red-600'
}

function clipScoreBg(score: number): string {
  if (score >= 0.10) return 'bg-emerald-50 border-emerald-100'
  if (score >= 0.08) return 'bg-green-50 border-green-100'
  if (score >= 0.06) return 'bg-yellow-50 border-yellow-100'
  return 'bg-red-50 border-red-100'
}

function clipScoreLabel(score: number): string {
  if (score >= 0.10) return 'Highest'
  if (score >= 0.08) return 'High'
  if (score >= 0.06) return 'Medium'
  return 'Low'
}

interface VideoPlayerHandle {
  seekTo: (time: number) => void
}

const StableVideoPlayer = forwardRef<VideoPlayerHandle, {
  src: string
  className?: string
  controls?: boolean
}>(function StableVideoPlayer({ src, className = '', controls = true }, ref) {
  const videoRef = useRef<HTMLVideoElement>(null)
  const currentSrcRef = useRef('')
  const [status, setStatus] = useState<'idle' | 'loading' | 'ready' | 'error'>('idle')

  useImperativeHandle(ref, () => ({
    seekTo(time: number) {
      const el = videoRef.current
      if (el) {
        el.currentTime = time
        el.play().catch(() => {})
      }
    },
  }))

  useEffect(() => {
    const el = videoRef.current
    if (!el || !src) {
      if (!src) setStatus('idle')
      return
    }
    if (currentSrcRef.current === src) return
    currentSrcRef.current = src
    setStatus('loading')
    el.src = src
    el.load()
  }, [src])

  const handleCanPlay = useCallback(() => setStatus('ready'), [])
  const handleError = useCallback(() => {
    if (currentSrcRef.current) setStatus('error')
  }, [])
  const handleRetry = useCallback(() => {
    const el = videoRef.current
    if (el && currentSrcRef.current) {
      setStatus('loading')
      el.load()
    }
  }, [])

  return (
    <div className="relative aspect-video bg-gray-800 flex items-center justify-center overflow-hidden">
      {src ? (
        <video
          ref={videoRef}
          className={`w-full h-full object-cover ${status === 'ready' ? 'opacity-100' : 'opacity-0'} transition-opacity duration-300 ${className}`}
          controls={controls}
          playsInline
          preload="metadata"
          onCanPlay={handleCanPlay}
          onError={handleError}
        />
      ) : null}

      {(status === 'idle' || status === 'loading') && (
        <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
          {status === 'loading' ? (
            <div className="w-10 h-10 border-3 border-white/30 border-t-white rounded-full animate-spin" />
          ) : (
            <div className="w-14 h-14 rounded-full bg-surface/20 backdrop-blur-sm flex items-center justify-center">
              <svg className="w-7 h-7 text-brand-white ml-1" fill="currentColor" viewBox="0 0 24 24">
                <path d="M8 5v14l11-7z" />
              </svg>
            </div>
          )}
        </div>
      )}

      {status === 'error' && (
        <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 pointer-events-auto">
          <svg className="w-8 h-8 text-white/50" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 9v3m0 3h.01M5.07 19h13.86c1.54 0 2.5-1.67 1.73-3L13.73 4c-.77-1.33-2.69-1.33-3.46 0L3.34 16c-.77 1.33.19 3 1.73 3z" />
          </svg>
          <p className="text-sm text-white/60">Video failed to load</p>
          <button
            type="button"
            onClick={handleRetry}
            className="px-3 py-1.5 rounded-lg bg-white/10 hover:bg-white/20 text-sm text-white/80 transition-colors"
          >
            Retry
          </button>
        </div>
      )}
    </div>
  )
})

export default function VideoAnalysis() {
  const { videoId } = useParams<{ videoId: string }>()
  const location = useLocation()
  const navState = (location.state || {}) as { searchClips?: ClipMatch[]; searchScore?: number; searchQuery?: string }
  const { getVideo, refresh: refreshCache } = useVideoCache()

  const { searchClips, searchQuery, hasSearchContext } = (() => {
    if (navState.searchClips && navState.searchClips.length > 0) {
      return {
        searchClips: navState.searchClips,
        searchQuery: navState.searchQuery || '',
        hasSearchContext: true,
      }
    }
    if (videoId) {
      try {
        const raw = sessionStorage.getItem(`vc_clips_${videoId}`)
        if (raw) {
          const parsed = JSON.parse(raw)
          if (Array.isArray(parsed.clips) && parsed.clips.length > 0) {
            return {
              searchClips: parsed.clips as ClipMatch[],
              searchQuery: (parsed.query || '') as string,
              hasSearchContext: false,
            }
          }
        }
      } catch { /* ignore */ }
    }
    return { searchClips: [] as ClipMatch[], searchQuery: '', hasSearchContext: false }
  })()
  const cachedVideo = videoId ? getVideo(videoId) : undefined
  const videoTitle = cachedVideo?.metadata?.filename || videoId || ''

  const rawAnalysis = cachedVideo?.metadata?.video_analysis as VideoAnalysisData | undefined
  const videoAnalysis: VideoAnalysisData = rawAnalysis?.title
    ? {
        title: rawAnalysis.title,
        description: rawAnalysis.description ?? '',
        categories: Array.isArray(rawAnalysis.categories) ? rawAnalysis.categories : [],
        topics: Array.isArray(rawAnalysis.topics) ? rawAnalysis.topics : [],
        people: Array.isArray((rawAnalysis as { people?: string[] }).people) ? (rawAnalysis as { people: string[] }).people : [],
        riskLevel: ['high', 'medium', 'low'].includes(rawAnalysis.riskLevel) ? rawAnalysis.riskLevel : 'medium',
        risks: Array.isArray(rawAnalysis.risks)
          ? rawAnalysis.risks.map((r: any) => ({
              label: r?.label ?? '',
              severity: ['high', 'medium', 'low'].includes(r?.severity) ? r.severity : 'medium',
              timestamp: r?.timestamp ?? r?.time ?? null,
            }))
          : [],
        transcript: Array.isArray(rawAnalysis.transcript)
          ? rawAnalysis.transcript.map((t: any) => ({ time: String(t?.time ?? '0:00'), text: String(t?.text ?? '') }))
          : [],
      }
    : DEFAULT_VIDEO_PLACEHOLDER

  const [generatingAnalysis, setGeneratingAnalysis] = useState(false)
  const [analysisError, setAnalysisError] = useState<string | null>(null)
  /** 0 = idle, 1 = content analysis, 2 = people & objects (unified flow) */
  const [analysisStep, setAnalysisStep] = useState<0 | 1 | 2>(0)

  async function generateAnalysis() {
    if (!videoId) return
    setAnalysisError(null)
    setGeneratingAnalysis(true)
    try {
      const res = await fetch(`${API_BASE}/api/videos/${encodeURIComponent(videoId)}/analysis`, { method: 'POST' })
      const data = await res.json().catch(() => ({}))
      if (!res.ok) {
        setAnalysisError(data?.error ?? `HTTP ${res.status}`)
        return
      }
      await refreshCache(true)
    } catch (e: any) {
      setAnalysisError(e?.message ?? 'Request failed')
    } finally {
      setGeneratingAnalysis(false)
    }
  }

  /** Append transcript from the last segment timestamp to the end of the video. */
  async function appendTranscriptFrom(lastSegmentSeconds: number) {
    if (!videoId || lastSegmentSeconds < 0) return
    setAppendTranscriptError(null)
    setAppendTranscriptLoading(true)
    try {
      const res = await fetch(`${API_BASE}/api/videos/${encodeURIComponent(videoId)}/transcript`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ append_from_seconds: lastSegmentSeconds }),
      })
      const data = await res.json().catch(() => ({}))
      if (!res.ok) throw new Error(data?.error ?? `HTTP ${res.status}`)
      await refreshCache(true)
    } catch (e: any) {
      setAppendTranscriptError(e?.message ?? 'Failed to append transcript')
    } finally {
      setAppendTranscriptLoading(false)
    }
  }

  const stableUrlRef = useRef<{ id: string; url: string }>({ id: '', url: '' })
  const videoStreamUrl = (() => {
    const freshUrl = cachedVideo?.stream_url || ''
    if (videoId && videoId !== stableUrlRef.current.id) {
      stableUrlRef.current = { id: videoId, url: freshUrl }
    } else if (videoId && !stableUrlRef.current.url && freshUrl) {
      stableUrlRef.current = { id: videoId, url: freshUrl }
    }
    return stableUrlRef.current.url
  })()

  const [insights, setInsights] = useState<VideoInsights | null>(null)
  const [insightsLoading, setInsightsLoading] = useState(false)
  const [insightsError, setInsightsError] = useState<string | null>(null)
  const [generatingInsights, setGeneratingInsights] = useState(false)

  const people: PersonEntry[] = insights?.people?.map((p) => ({
    id: p.entity_id,
    name: p.name,
    avatar: p.avatar,
    percent: p.percent,
    face_snap_base64: p.face_snap_base64,
    face_from_video_base64: p.face_from_video_base64,
    clips: p.clips || [],
  })) ?? []
  const detectedFaces: DetectedFace[] = insights?.detected_faces ?? []
  const mentionedNames: string[] = insights?.mentioned ?? []
  const objectsList: ObjectInsight[] = insights?.objects ?? []
  const linkDataByEntity: Record<string, PersonLinkData> = insights?.link_data_by_entity ?? {}
  const videoDurationSec = insights?.video_duration_sec ?? 0
  const hasDetectedFaces = detectedFaces.length > 0
  const peopleCount = hasDetectedFaces ? detectedFaces.length : people.length

  const [selectedPerson, setSelectedPerson] = useState<PersonEntry | null>(null)
  const [selectedFaceIdx, setSelectedFaceIdx] = useState<number | null>(null)
  useEffect(() => {
    if (people.length > 0 && (!selectedPerson || !people.find((p) => p.id === selectedPerson.id)))
      setSelectedPerson(people[0])
    else if (people.length === 0) setSelectedPerson(null)
  }, [insights?.people?.length, insights?.people?.map((p) => p.entity_id).join(',')])
  useEffect(() => {
    if (hasDetectedFaces && (selectedFaceIdx === null || selectedFaceIdx >= detectedFaces.length))
      setSelectedFaceIdx(0)
    else if (!hasDetectedFaces) setSelectedFaceIdx(null)
  }, [hasDetectedFaces, detectedFaces.length])

  const [activeObjectIdx, setActiveObjectIdx] = useState(0)
  const [reportModalOpen, setReportModalOpen] = useState(false)
  const [linkAnalysisPersonId, setLinkAnalysisPersonId] = useState<string | null>(null)
  const [editingPersonId, setEditingPersonId] = useState<string | null>(null)
  const [editName, setEditName] = useState('')
  const [showAllTranscript, setShowAllTranscript] = useState(false)
  const [appendTranscriptLoading, setAppendTranscriptLoading] = useState(false)
  const [appendTranscriptError, setAppendTranscriptError] = useState<string | null>(null)
  const playerRef = useRef<VideoPlayerHandle>(null)
  const sidebarPlayerRef = useRef<VideoPlayerHandle>(null)
  const [chatPanelOpen, setChatPanelOpen] = useState(false)
  const [activeClipIdx, setActiveClipIdx] = useState<number | null>(null)
  const [clipThumbnails, setClipThumbnails] = useState<Record<number, string>>({})
  const thumbnailVideoRef = useRef<HTMLVideoElement>(null)
  const thumbnailCanvasRef = useRef<HTMLCanvasElement>(null)
  const captureIndexRef = useRef(0)
  const [isLgViewport, setIsLgViewport] = useState(() => typeof window !== 'undefined' && window.matchMedia('(min-width: 1024px)').matches)

  useEffect(() => {
    if (videoId && !cachedVideo) refreshCache(true)
  }, [videoId, cachedVideo, refreshCache])

  useEffect(() => {
    if (!videoId) return
    setInsightsLoading(true)
    setInsightsError(null)
    fetch(`${API_BASE}/api/videos/${encodeURIComponent(videoId)}/insights`)
      .then((r) => {
        if (r.ok) return r.json()
        if (r.status === 404) return null
        throw new Error(r.statusText || 'Failed to fetch insights')
      })
      .then((data) => {
        if (data?.insights) setInsights(data.insights)
        else setInsights(null)
      })
      .catch((e) => {
        setInsightsError(e?.message ?? 'Failed to load insights')
        setInsights(null)
      })
      .finally(() => setInsightsLoading(false))
  }, [videoId])

  async function generateInsights() {
    if (!videoId) return
    setInsightsError(null)
    setGeneratingInsights(true)
    try {
      const res = await fetch(`${API_BASE}/api/videos/${encodeURIComponent(videoId)}/insights`, { method: 'POST' })
      const data = await res.json().catch(() => ({}))
      if (!res.ok) throw new Error(data?.error ?? `HTTP ${res.status}`)
      if (data.insights) setInsights(data.insights)
    } catch (e: any) {
      setInsightsError(e?.message ?? 'Failed to generate insights')
    } finally {
      setGeneratingInsights(false)
    }
  }

  /** Single entry point: run content analysis then people/objects insights; updates analysisStep for UI */
  async function runFullAnalysis() {
    if (!videoId) return
    setAnalysisError(null)
    setInsightsError(null)
    setAnalysisStep(1)
    try {
      await generateAnalysis()
      setAnalysisStep(2)
      await generateInsights()
    } finally {
      setAnalysisStep(0)
    }
  }

  useEffect(() => {
    const mq = window.matchMedia('(min-width: 1024px)')
    const handler = () => setIsLgViewport(mq.matches)
    mq.addEventListener('change', handler)
    return () => mq.removeEventListener('change', handler)
  }, [])

  // Generate thumbnails for each clip (frame at clip.start)
  useEffect(() => {
    if (!videoStreamUrl || searchClips.length === 0) {
      setClipThumbnails({})
      return
    }
    const video = thumbnailVideoRef.current
    const canvas = thumbnailCanvasRef.current
    if (!video || !canvas) return
    const ctx = canvas.getContext('2d')
    if (!ctx) return

    setClipThumbnails({})
    const clips = searchClips

    const onSeeked = () => {
      const i = captureIndexRef.current
      if (i >= clips.length) return
      if (video.videoWidth && video.videoHeight) {
        canvas.width = video.videoWidth
        canvas.height = video.videoHeight
        ctx.drawImage(video, 0, 0)
        try {
          const dataUrl = canvas.toDataURL('image/jpeg', 0.85)
          setClipThumbnails((prev) => ({ ...prev, [i]: dataUrl }))
        } catch {
          // ignore
        }
      }
      const next = i + 1
      if (next < clips.length) {
        captureIndexRef.current = next
        video.currentTime = clips[next].start
      }
    }

    const onLoadedData = () => {
      captureIndexRef.current = 0
      video.currentTime = clips[0].start
    }

    video.addEventListener('seeked', onSeeked)
    video.addEventListener('loadeddata', onLoadedData, { once: true })
    video.src = videoStreamUrl
    video.load()

    return () => {
      video.removeEventListener('seeked', onSeeked)
      video.removeEventListener('loadeddata', onLoadedData)
      video.src = ''
    }
  }, [videoStreamUrl, searchClips])

  function startEditing(p: PersonEntry) {
    setEditingPersonId(p.id)
    setEditName(p.name)
  }

  function commitEdit(personId: string) {
    const trimmed = editName.trim()
    if (trimmed && insights?.people) {
      const updated = insights.people.map((p) =>
        p.entity_id === personId
          ? { ...p, name: trimmed, avatar: trimmed.split(' ').map((w) => w[0]?.toUpperCase() ?? '').join('').slice(0, 2) }
          : p
      )
      setInsights((prev) => (prev ? { ...prev, people: updated } : null))
      if (selectedPerson?.id === personId) {
        setSelectedPerson((prev) => (prev ? { ...prev, name: trimmed, avatar: trimmed.split(' ').map((w) => w[0]?.toUpperCase() ?? '').join('').slice(0, 2) } : null))
      }
    }
    setEditingPersonId(null)
    setEditName('')
  }

  const timelineSegments: number[] = (() => {
    const dur = videoDurationSec || 60
    const n = 20
    const segDur = dur / n
    const clips = selectedPerson?.clips ?? []
    return Array.from({ length: n }, (_, i) => {
      const t0 = i * segDur
      const t1 = (i + 1) * segDur
      return clips.some((c) => c.end > t0 && c.start < t1) ? 1 : 0
    })
  })()

  return (
    <div className="flex flex-col h-full">
      <div className="px-3 sm:px-6 pt-4 sm:pt-5 pb-3 flex flex-wrap items-center justify-between gap-3 shrink-0">
        <div className="flex items-center gap-2 sm:gap-3 text-sm min-w-0 flex-1">
          <Link
            to="/dashboard"
            className="inline-flex items-center gap-2 px-3 sm:px-4 py-2 rounded-full border border-border bg-surface text-sm font-medium text-text-secondary hover:border-accent hover:bg-accent/5 hover:text-text-primary transition-colors shrink-0 no-underline"
            aria-label="Back to search"
          >
            <svg className="w-4 h-4 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
              <path d="M19 12H5M12 19l-7-7 7-7" />
            </svg>
            Back to search
          </Link>
          <span className="text-gray-400 shrink-0 hidden sm:inline" aria-hidden>/</span>
          <span className="text-gray-700 font-medium truncate">{videoTitle || `Video ${videoId}`}</span>
        </div>
        <button
          type="button"
          onClick={() => setChatPanelOpen(true)}
          className="inline-flex items-center gap-2 px-3 sm:px-4 py-2 rounded-full border border-border bg-surface text-sm font-medium text-text-secondary hover:border-accent hover:bg-accent/5 hover:text-text-primary transition-colors shrink-0"
        >
          <svg className="w-4 h-4 text-gray-500 shrink-0" viewBox="0 0 12 12.0376" fill="currentColor" aria-hidden>
            <path fillRule="evenodd" clipRule="evenodd" d="M8.8 1H3.2C1.98497 1 1 1.98497 1 3.2V6.13333C1 7.34836 1.98497 8.33333 3.2 8.33333H3.92451C4.32261 8.33333 4.69151 8.54221 4.89633 8.88357L6 10.723L7.10367 8.88357C7.30849 8.5422 7.6774 8.33333 8.07549 8.33333H8.8C10.015 8.33333 11 7.34836 11 6.13333V3.2C11 1.98497 10.015 1 8.8 1ZM3.2 0C1.43269 0 0 1.43269 0 3.2V6.13333C0 7.90065 1.43269 9.33333 3.2 9.33333H3.92451C3.97134 9.33333 4.01474 9.35791 4.03884 9.39807L5.42834 11.7139C5.68727 12.1455 6.31273 12.1455 6.57166 11.7139L7.96116 9.39807C7.98526 9.35791 8.02866 9.33333 8.07549 9.33333H8.8C10.5673 9.33333 12 7.90064 12 6.13333V3.2C12 1.43269 10.5673 0 8.8 0H3.2Z" />
          </svg>
          Ask about this video
        </button>
      </div>

      {chatPanelOpen && (
        <>
          <div
            className="fixed inset-0 bg-brand-charcoal/40 backdrop-blur-sm z-40"
            aria-hidden
            onClick={() => setChatPanelOpen(false)}
          />
          <div className="fixed inset-0 z-50 flex flex-col lg:flex-row pointer-events-none">
            <div
              className="flex-1 min-w-0 flex items-center justify-center p-3 sm:p-6 pointer-events-auto"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex flex-col items-center gap-3 w-full max-w-[560px]">
                <div className="rounded-xl overflow-hidden bg-brand-charcoal shadow-lg w-full shrink-0">
                  <StableVideoPlayer ref={sidebarPlayerRef} src={videoStreamUrl} />
                </div>
                <p className="text-sm text-gray-600 truncate w-full text-center">{videoTitle || `Video ${videoId}`}</p>
              </div>
            </div>
            <div
              className="w-full lg:max-w-lg bg-background border-t lg:border-t-0 lg:border-l border-border shadow-lg flex flex-col shrink-0 pointer-events-auto max-h-[70vh] lg:max-h-none"
              onClick={(e) => e.stopPropagation()}
            >
              <Chatbot
                fixedVideoId={videoId ?? ''}
                onClose={() => setChatPanelOpen(false)}
                onSeekToTime={(seconds) => {
                  const player = sidebarPlayerRef.current ?? playerRef.current
                  player?.seekTo(seconds)
                }}
              />
            </div>
          </div>
        </>
      )}

      <div className="flex flex-col lg:flex-row flex-1 overflow-hidden px-3 sm:px-6 pb-4 sm:pb-6 gap-4 lg:gap-6">

        <div className="flex-1 overflow-y-auto min-w-0 pr-0 lg:pr-2 order-2 lg:order-1">

          {!rawAnalysis?.title ? (
            /* Empty state — Strand: typography, radii, shadows, product/accent colors, icons */
            <div className="py-6 sm:py-8 w-full">
              <h2 className="font-brand text-h5 sm:text-h4 font-medium text-text-primary tracking-tight mb-1">
                Analyze this video
              </h2>
              <p className="text-base text-text-secondary leading-relaxed mb-6">
                Get a structured report with description, categories, topics, risks, people, detected objects, and transcript.
              </p>

              {/* Analyzing in progress — Strand-style loader card */}
              {(analysisStep === 1 || analysisStep === 2) && (
                <div
                  className="mb-6 rounded-xl border-2 border-[var(--strand-ui-accent)] bg-[var(--strand-ui-accent-light)] px-5 py-4 flex items-center gap-4 shadow-sm"
                  role="status"
                  aria-live="polite"
                  aria-label={analysisStep === 1 ? 'Analyzing video content' : 'Detecting people and objects'}
                >
                  <span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-brand-charcoal text-brand-white">
                    <img src={spinnerIconUrl} alt="" className="w-6 h-6 animate-spin opacity-90 invert" aria-hidden />
                  </span>
                  <div className="min-w-0">
                    <p className="font-brand text-base font-semibold text-text-primary">
                      {analysisStep === 1 ? 'Analyzing video content…' : 'Detecting people and objects…'}
                    </p>
                    <p className="text-sm text-text-secondary mt-0.5">
                      {analysisStep === 1
                        ? 'Generating description, categories, risks, and transcript. This may take 1–2 minutes.'
                        : 'Finding faces and objects in the video. Almost done.'}
                    </p>
                  </div>
                </div>
              )}

              {/* Primary CTA — prominent placement so user focuses on it first */}
              <div className="mb-8">
                <button
                  type="button"
                  onClick={runFullAnalysis}
                  disabled={analysisStep !== 0}
                  className="w-full sm:w-auto min-w-[200px] inline-flex items-center justify-center gap-2 h-11 px-6 rounded-xl bg-brand-charcoal text-brand-white font-brand font-semibold text-base hover:bg-gray-300 hover:text-brand-charcoal disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:bg-brand-charcoal disabled:hover:text-brand-white transition-colors duration-200 shadow-md hover:shadow-lg focus:outline-none focus:ring-2 focus:ring-accent focus:ring-offset-2"
                >
                  {analysisStep !== 0 ? (
                    <>
                      <img src={spinnerIconUrl} alt="" className="w-4 h-4 animate-spin opacity-90 invert" aria-hidden />
                      {analysisStep === 1 ? 'Analyzing…' : 'Detecting…'}
                    </>
                  ) : (
                    'Generate Analysis'
                  )}
                </button>
                {(analysisError || insightsError) && (
                  <p className="mt-3 text-sm text-error" role="alert">{analysisError || insightsError}</p>
                )}
              </div>

              <div className="mb-8">
                <p className="font-brand-xbold text-sm text-text-secondary uppercase tracking-wider mb-4">
                  What you&apos;ll get
                </p>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
                  {ANALYSIS_SECTIONS.map(({ id, label, desc, iconUrl, iconBg }) => (
                    <div
                      key={id}
                      className="group flex flex-col rounded-xl border border-border bg-accent/5 overflow-hidden text-left transition-all duration-200 hover:shadow-md hover:border-accent/30"
                    >
                      <div className="flex flex-col gap-3 p-4 min-h-[120px]">
                        <span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-border shadow-sm ${iconBg}`}>
                          <img src={iconUrl} alt="" className="w-5 h-5" aria-hidden />
                        </span>
                        <div className="flex flex-col gap-0.5 min-w-0">
                          <span className="font-brand text-sm font-semibold text-text-primary leading-tight">{label}</span>
                          <span className="text-xs text-text-secondary leading-snug">{desc}</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* What analysis includes: two blocks (no step framing), People vs Objects explained */}
              <div className="space-y-4 mb-6">
                {/* Block 1: Content overview */}
                <div className={`rounded-xl border-2 px-4 py-4 transition-all duration-200 ${
                  analysisStep === 1 ? 'border-accent bg-[var(--strand-ui-accent-light)] shadow-md' : 'border-border bg-card'
                }`}>
                  <div className="flex items-start gap-4">
                    <span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${
                      analysisStep === 1 ? 'bg-brand-charcoal' : 'bg-[var(--strand-product-generate-light)] border border-border'
                    }`}>
                      {analysisStep === 1 ? (
                        <img src={spinnerIconUrl} alt="" className="w-5 h-5 animate-spin opacity-90" aria-hidden />
                      ) : analysisStep >= 2 ? (
                        <img src={checkmarkIconUrl} alt="" className="w-5 h-5" aria-hidden />
                      ) : (
                        <img src={documentListIconUrl} alt="" className="w-5 h-5" aria-hidden />
                      )}
                    </span>
                    <div className="min-w-0 flex-1">
                      <p className="font-brand text-base font-medium text-text-primary">Content overview</p>
                      <p className="text-sm text-text-secondary mt-1">
                        A written description of the video, categories and topics, risk level and issues, plus a full transcript with timestamps.
                      </p>
                    </div>
                  </div>
                </div>

                {/* Block 2: People & objects — split so user understands both */}
                <div className={`rounded-xl border-2 px-4 py-4 transition-all duration-200 ${
                  analysisStep === 2 ? 'border-accent bg-[var(--strand-ui-accent-light)] shadow-md' : 'border-border bg-card'
                }`}>
                  <div className="flex items-start gap-4">
                    <span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${
                      analysisStep === 2 ? 'bg-brand-charcoal' : 'bg-[var(--strand-product-embed-light)] border border-border'
                    }`}>
                      {analysisStep === 2 ? (
                        <img src={spinnerIconUrl} alt="" className="w-5 h-5 animate-spin opacity-90" aria-hidden />
                      ) : (
                        <img src={entityIconUrl} alt="" className="w-5 h-5" aria-hidden />
                      )}
                    </span>
                    <div className="min-w-0 flex-1 space-y-3">
                      <div>
                        <p className="font-brand text-base font-medium text-text-primary">People & detected objects</p>
                        <p className="text-sm text-text-secondary mt-1">
                          Visual and speech-based insights from the video:
                        </p>
                      </div>
                      <ul className="space-y-2 text-sm">
                        <li className="flex items-start gap-2">
                          <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-md bg-[var(--strand-ui-accent-light)] mt-0.5">
                            <img src={entityIconUrl} alt="" className="w-3 h-3" aria-hidden />
                          </span>
                          <span>
                            <strong className="font-medium text-text-primary">People</strong>
                            <span className="text-text-secondary"> — Faces found in the video, who appears when, and names mentioned in speech (e.g. in the transcript).</span>
                          </span>
                        </li>
                        <li className="flex items-start gap-2">
                          <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-md bg-[var(--strand-product-embed-light)] mt-0.5">
                            <img src={visionIconUrl} alt="" className="w-3 h-3" aria-hidden />
                          </span>
                          <span>
                            <strong className="font-medium text-text-primary">Detected objects</strong>
                            <span className="text-text-secondary"> — Items and objects spotted in frames (e.g. equipment, signs, hazards) with timestamps and thumbnails so you can jump to the moment.</span>
                          </span>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>

              {(analysisStep === 1 || analysisStep === 2) && (
                <div className="rounded-xl border border-border bg-card shadow-sm px-5 py-4 mb-6 flex items-center gap-4">
                  <span className="w-11 h-11 shrink-0 rounded-xl bg-[var(--strand-ui-accent-light)] flex items-center justify-center">
                    <img src={spinnerIconUrl} alt="" className="w-5 h-5 animate-spin text-accent" aria-hidden />
                  </span>
                  <div>
                    <p className="font-brand text-base font-medium text-text-primary">
                      {analysisStep === 1 ? 'Analyzing video content…' : 'Detecting people and objects…'}
                    </p>
                    <p className="text-sm text-text-secondary mt-0.5">
                      {analysisStep === 1 ? 'Generating description, categories, and risks.' : 'This may take a moment.'}
                    </p>
                  </div>
                </div>
              )}
            </div>
          ) : (
            <>
          <Section title="Video description" color="bg-accent">
              <>
                <div className="flex flex-wrap items-start justify-between gap-2 mb-2">
                  <h4 className="text-base font-semibold text-gray-700 w-fit max-w-full pr-4">{toTitleCase(videoAnalysis.title)}</h4>
                  <button
                    type="button"
                    onClick={generateAnalysis}
                    disabled={generatingAnalysis}
                    className="text-xs font-medium text-accent hover:underline disabled:opacity-60 shrink-0"
                  >
                    {generatingAnalysis ? 'Regenerating…' : 'Regenerate analysis'}
                  </button>
                </div>
                <p className="text-base text-gray-600 leading-relaxed">{videoAnalysis.description}</p>
              </>
          </Section>

          {rawAnalysis?.title && (
            <>
              <Section title="Categories" badge={videoAnalysis.categories.length} color="bg-accent">
                <div className="flex flex-wrap gap-2">
                  {videoAnalysis.categories.map((cat) => (
                    <span
                      key={cat}
                      className="inline-flex items-center px-3 py-1.5 rounded-md bg-gray-100 text-sm text-gray-700 font-medium"
                    >
                      {cat}
                    </span>
                  ))}
                </div>
              </Section>

              <Section title="About topic" badge={videoAnalysis.topics.length} color="bg-accent">
                <div className="flex flex-wrap gap-2">
                  {videoAnalysis.topics.map((topic) => (
                    <Tag key={topic} label={topic} />
                  ))}
                </div>
              </Section>

              <Section title="Risk involved" badge={videoAnalysis.risks.length} color="bg-error">
                <div className="flex flex-wrap items-center gap-2 sm:gap-3 mb-4">
                  <RiskLevel level={videoAnalysis.riskLevel} />
                  <span className="text-sm text-gray-500">{videoAnalysis.risks.length} issues identified</span>
                </div>
                <ul className="space-y-2">
                  {videoAnalysis.risks.map((risk, i) => (
                    <li
                      key={i}
                      className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-surface border border-border px-3 sm:px-4 py-3"
                    >
                      <span className="text-sm text-gray-700 flex-1 min-w-0">{risk.label}</span>
                      <div className="flex items-center gap-2 shrink-0">
                        <RiskBadge severity={risk.severity} />
                      </div>
                    </li>
                  ))}
                </ul>
              </Section>
            </>
          )}

          <Section
            title="People"
            badge={peopleCount + mentionedNames.length}
            color="bg-accent"
          >
            {insightsLoading && !insights ? (
              <p className="text-sm text-gray-500">Loading insights…</p>
            ) : !insights && !generatingInsights ? (
              <div>
                <p className="text-sm text-gray-500 mb-3">Generate insights to detect faces and objects in this video. Run after the video is indexed.</p>
                <button
                  type="button"
                  onClick={generateInsights}
                  disabled={generatingInsights}
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-accent text-white text-sm font-medium hover:bg-accent/90 disabled:opacity-60"
                >
                  {generatingInsights ? (
                    <>
                      <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      Generating insights…
                    </>
                  ) : (
                    'Generate insights'
                  )}
                </button>
                {insightsError && <p className="mt-2 text-sm text-red-600" role="alert">{insightsError}</p>}
              </div>
            ) : (
              <>
                <div className="flex flex-wrap items-center justify-between gap-2 mb-2">
                  <p className="text-xs text-gray-500">
                    {hasDetectedFaces ? `Detected faces (${detectedFaces.length})` : `Shown people (${people.length})`}
                  </p>
                  <button
                    type="button"
                    onClick={generateInsights}
                    disabled={generatingInsights}
                    className="text-xs font-medium text-accent hover:underline disabled:opacity-60"
                  >
                    {generatingInsights ? 'Regenerating…' : 'Regenerate insights'}
                  </button>
                </div>

                {hasDetectedFaces ? (
                  <>
                    <div className="flex flex-wrap gap-4 mb-4 p-1 -m-1">
                      {detectedFaces.map((face, idx) => (
                        <div key={face.face_id} className="flex flex-col items-center gap-1">
                          <button
                            type="button"
                            onClick={() => setSelectedFaceIdx(idx)}
                            className={`rounded-full ring-2 ring-offset-2 transition-all duration-200 shrink-0 ${
                              selectedFaceIdx === idx ? 'ring-accent' : 'ring-transparent hover:ring-gray-300'
                            }`}
                          >
                            <div className="w-14 h-14 rounded-full overflow-hidden bg-gray-200 shrink-0 ring-1 ring-gray-300">
                              <img
                                src={`data:image/png;base64,${face.image_base64}`}
                                alt={`Face ${face.face_id + 1}`}
                                className="w-full h-full object-cover"
                              />
                            </div>
                          </button>
                          <span className="text-[10px] text-gray-500">
                            Face {face.face_id + 1} · {(face.confidence * 100).toFixed(0)}%
                          </span>
                        </div>
                      ))}
                    </div>
                  </>
                ) : (
                  <>
                    <div className="flex flex-wrap gap-3 mb-4 p-1 -m-1">
                      {people.map((p) => {
                        const isEditing = editingPersonId === p.id
                        return (
                          <div key={p.id} className="relative group flex flex-col items-center gap-1">
                            <button
                              type="button"
                              onClick={() => setSelectedPerson(p)}
                              className={`relative rounded-full ring-2 ring-offset-2 transition-all duration-200 ${
                                selectedPerson?.id === p.id ? 'ring-accent' : 'ring-transparent hover:ring-gray-300'
                              }`}
                            >
                              <Avatar initials={p.avatar} size="sm" imageBase64={p.face_from_video_base64 ?? undefined} />
                              <span
                                role="button"
                                tabIndex={0}
                                onClick={(e) => { e.stopPropagation(); startEditing(p) }}
                                onKeyDown={(e) => { if (e.key === 'Enter') { e.stopPropagation(); startEditing(p) } }}
                                className="absolute -top-1 -right-1 w-5 h-5 rounded-full bg-surface border border-border shadow-sm flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer"
                                aria-label={`Edit name for ${p.name}`}
                              >
                                <svg className="w-2.5 h-2.5 text-gray-500" viewBox="0 0 12 12" fill="currentColor">
                                  <path d="M9.08 0.293a1 1 0 011.414 0l1.213 1.213a1 1 0 010 1.414L4.586 10.04 0 12l1.96-4.586L9.08.293zM2.72 7.866l-1.04 2.434 2.434-1.04 6.453-6.453-1.394-1.394L2.72 7.866z" />
                                </svg>
                              </span>
                            </button>
                            {isEditing ? (
                              <input
                                autoFocus
                                value={editName}
                                onChange={(e) => setEditName(e.target.value)}
                                onBlur={() => commitEdit(p.id)}
                                onKeyDown={(e) => { if (e.key === 'Enter') commitEdit(p.id); if (e.key === 'Escape') setEditingPersonId(null) }}
                                className="w-20 text-[10px] text-center text-text-primary border border-accent rounded px-1 py-0.5 focus:outline-none focus:ring-1 focus:ring-accent bg-surface"
                              />
                            ) : (
                              <span
                                className="text-[10px] text-gray-500 truncate max-w-[64px] cursor-pointer hover:text-gray-700"
                                onClick={() => startEditing(p)}
                                title={`Click to edit: ${p.name}`}
                              >
                                {p.name}
                              </span>
                            )}
                          </div>
                        )
                      })}
                    </div>
                    {selectedPerson && (
                      <div className="flex flex-wrap items-center gap-3">
                        <Avatar initials={selectedPerson.avatar} size="md" imageBase64={selectedPerson.face_from_video_base64 ?? undefined} />
                        <div className="flex-1 min-w-0">
                          <p className="text-base font-semibold text-gray-700">{selectedPerson.name}</p>
                          <p className="text-sm text-gray-500">
                            Appears in {selectedPerson.percent}% of video
                          </p>
                        </div>
                        <button
                          type="button"
                          onClick={() => setLinkAnalysisPersonId(selectedPerson.id)}
                          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border bg-surface text-xs font-medium text-text-secondary hover:border-border-light hover:bg-card transition-colors shrink-0 w-full sm:w-auto"
                        >
                          <svg className="w-3.5 h-3.5" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.5">
                            <circle cx="3" cy="6" r="2" />
                            <circle cx="9" cy="3" r="2" />
                            <circle cx="9" cy="9" r="2" />
                            <line x1="4.8" y1="5.2" x2="7.2" y2="3.8" />
                            <line x1="4.8" y1="6.8" x2="7.2" y2="8.2" />
                          </svg>
                          Link Analysis
                        </button>
                      </div>
                    )}
                  </>
                )}

                {mentionedNames.length > 0 && (
                  <>
                    <p className="text-xs text-gray-500 mb-2">
                      Mentioned people ({mentionedNames.length})
                    </p>
                    <div className="flex gap-2 mb-5">
                      {mentionedNames.map((name) => (
                        <Tag key={name} label={name} />
                      ))}
                    </div>
                  </>
                )}

                {!hasDetectedFaces && <TimelineBar segments={timelineSegments} durationSeconds={videoDurationSec} />}
              </>
            )}
          </Section>

          <Section
            title="Detected objects"
            badge={objectsList.length}
            color="bg-accent"
          >
            {!insights ? (
              <p className="text-sm text-gray-500">Generate insights to see detected objects with timestamps and frames.</p>
            ) : (
              <>
                <div className="flex flex-wrap gap-2 mb-4">
                  {objectsList.map((obj, i) => (
                    <button key={`${obj.object}-${obj.timestamp}-${i}`} type="button" onClick={() => setActiveObjectIdx(i)}>
                      <Tag label={obj.object} active={i === activeObjectIdx} />
                    </button>
                  ))}
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
                  {objectsList.map((obj, i) => {
                    const ts = obj.timestamp
                    const timeStr = fmtSec(ts)
                    const frameUrl = obj.frame_url ? `${API_BASE}${obj.frame_url}` : null
                    const bbox = obj.bbox
                    return (
                      <div
                        key={`${obj.object}-${ts}-${i}`}
                        className={`rounded-lg border overflow-hidden bg-card ${i === activeObjectIdx ? 'ring-2 ring-accent border-accent' : 'border-border'}`}
                      >
                        <button
                          type="button"
                          className="w-full text-left"
                          onClick={() => {
                            setActiveObjectIdx(i)
                            if (Number.isFinite(ts)) playerRef.current?.seekTo(ts)
                          }}
                        >
                          <div className="aspect-video bg-gray-100 flex items-center justify-center overflow-hidden relative">
                            {frameUrl ? (
                              <>
                                <img src={frameUrl} alt="" className="w-full h-full object-cover" />
                                {bbox && (
                                  <span
                                    className="absolute border-2 border-accent pointer-events-none"
                                    style={{
                                      left: `${bbox.left * 100}%`,
                                      top: `${bbox.top * 100}%`,
                                      width: `${bbox.width * 100}%`,
                                      height: `${bbox.height * 100}%`,
                                    }}
                                    aria-hidden
                                  />
                                )}
                              </>
                            ) : (
                              <span className="text-xs text-gray-400">{timeStr}</span>
                            )}
                          </div>
                          <div className="px-2 py-2 flex items-center justify-between gap-2">
                            <span className="text-sm font-medium text-gray-700 truncate">{obj.object}</span>
                            <span className="text-xs font-mono text-accent shrink-0" title="Go to time">{timeStr}</span>
                          </div>
                        </button>
                      </div>
                    )
                  })}
                </div>
              </>
            )}
          </Section>
            </>
          )}
        </div>

        <div className="w-full lg:w-[420px] shrink-0 flex flex-col gap-3 overflow-hidden order-1 lg:order-2 min-h-0">
          {/* Off-screen video + canvas for clip thumbnails (only when arrived from search) */}
          {hasSearchContext && searchClips.length > 0 && videoStreamUrl && (
            <div className="fixed -left-[9999px] w-px h-px overflow-hidden" aria-hidden>
              <video ref={thumbnailVideoRef} muted playsInline preload="metadata" crossOrigin="anonymous" />
              <canvas ref={thumbnailCanvasRef} />
            </div>
          )}

          <div className="rounded-xl overflow-hidden bg-brand-charcoal shadow-lg shrink-0">
            <StableVideoPlayer ref={playerRef} src={videoStreamUrl} />
          </div>

          <div className="flex flex-wrap items-center justify-between gap-2 shrink-0">
            <div className="flex items-center gap-2 min-w-0">
              <RiskLevel level={videoAnalysis.riskLevel} />

              <div className="relative group ml-1">
                <button
                  type="button"
                  className="p-1 rounded-md text-gray-400 hover:text-gray-700 hover:bg-gray-100 transition-colors duration-200"
                  aria-label="Video details"
                >
                  <svg className="w-4 h-4" viewBox="0 0 12 12" fill="currentColor">
                    <path d="M6.66699 9.33301H5.33301V5.33301H6.66699V9.33301Z" />
                    <path d="M6.66699 4H5.33301V2.66699H6.66699V4Z" />
                    <path fillRule="evenodd" clipRule="evenodd" d="M8.40039 0C10.3883 0.000211285 11.9998 1.61169 12 3.59961V8.40039C11.9998 10.3883 10.3883 11.9998 8.40039 12H3.59961C1.61169 11.9998 0.000211285 10.3883 0 8.40039V3.59961C0.000211156 1.61169 1.61169 0.000211157 3.59961 0H8.40039ZM3.59961 1C2.16398 1.00021 1.00021 2.16398 1 3.59961V8.40039C1.00021 9.83602 2.16398 10.9998 3.59961 11H8.40039C9.83602 10.9998 10.9998 9.83602 11 8.40039V3.59961C10.9998 2.16398 9.83602 1.00021 8.40039 1H3.59961Z" />
                  </svg>
                </button>

                <div className="absolute left-1/2 -translate-x-1/2 top-full mt-2 w-64 rounded-lg border border-gray-300 bg-surface p-4 shadow-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200 z-50">
                  <h4 className="text-base font-semibold text-gray-700 mb-2">Video details</h4>
                  <dl className="space-y-2 text-xs">
                    <div className="flex justify-between">
                      <dt className="text-gray-500">Video ID</dt>
                      <dd className="text-gray-700 font-mono">{videoId}</dd>
                    </div>
                    <div className="flex justify-between">
                      <dt className="text-gray-500">Duration</dt>
                      <dd className="text-gray-700">4:32</dd>
                    </div>
                    <div className="flex justify-between">
                      <dt className="text-gray-500">Resolution</dt>
                      <dd className="text-gray-700">1920 &times; 1080</dd>
                    </div>
                  </dl>
                  <div className="absolute left-1/2 -translate-x-1/2 -top-1.5 w-3 h-3 bg-surface border-l border-t border-gray-300 rotate-45" />
                </div>
              </div>
            </div>

            <div className="flex items-center gap-1.5 shrink-0">
              <Button variant="black" size="small" onClick={() => setReportModalOpen(true)} className="whitespace-nowrap">PDF Report</Button>
            </div>
          </div>
          <PdfReportModal
            open={reportModalOpen}
            onClose={() => setReportModalOpen(false)}
            videoId={videoId ?? ''}
            videoAnalysis={videoAnalysis}
            detectedFaces={insights?.detected_faces ?? []}
            objects={insights?.objects ?? []}
          />

          {hasSearchContext && searchClips.length > 0 && (() => {
            const maxScore = Math.max(...searchClips.map(c => c.score))
            const timelineEnd = searchClips.reduce((mx, c) => Math.max(mx, c.end), 0) * 1.15
            const rel = clipRelevance(searchClips)

            function scoreBarColor(score: number): string {
              if (score >= 0.10) return 'bg-emerald-500'
              if (score >= 0.08) return 'bg-green-500'
              if (score >= 0.06) return 'bg-amber-500'
              return 'bg-red-400'
            }

            return (
              <div className="rounded-xl overflow-hidden border border-border bg-surface shadow-sm shrink-0">
                {/* Header — Strand: search product tint, typography */}
                <div className="px-4 py-3.5 bg-[var(--strand-product-search-light)] border-b border-border">
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex items-center gap-3 min-w-0">
                      <div className="w-9 h-9 rounded-lg bg-[var(--strand-product-search)]/20 flex items-center justify-center shrink-0 border border-[var(--strand-product-search)]/30">
                        <svg className="w-4 h-4 text-[var(--strand-product-search-dark)]" viewBox="0 0 16 16" fill="none" aria-hidden>
                          <circle cx="7" cy="7" r="5" stroke="currentColor" strokeWidth="1.5"/>
                          <line x1="11" y1="11" x2="14" y2="14" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
                        </svg>
                      </div>
                      <div className="min-w-0">
                        <p className="font-brand text-sm font-semibold text-text-primary leading-tight truncate">
                          &ldquo;{searchQuery}&rdquo;
                        </p>
                        <p className="text-xs text-text-secondary mt-0.5">
                          {searchClips.length} clip{searchClips.length !== 1 ? 's' : ''} found
                        </p>
                      </div>
                    </div>
                    {rel.label && (
                      <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-semibold shrink-0 border ${
                        rel.label === 'Highest' ? 'bg-emerald-500/15 text-emerald-700 border-emerald-200' :
                        rel.label === 'High' ? 'bg-green-500/15 text-green-700 border-green-200' :
                        rel.label === 'Medium' ? 'bg-amber-500/15 text-amber-700 border-amber-200' :
                        'bg-red-500/15 text-red-700 border-red-200'
                      }`}>
                        <span className={`w-1.5 h-1.5 rounded-full ${
                          rel.label === 'Highest' ? 'bg-emerald-500' :
                          rel.label === 'High' ? 'bg-green-500' :
                          rel.label === 'Medium' ? 'bg-amber-500' : 'bg-red-500'
                        }`} />
                        {rel.label}
                      </span>
                    )}
                  </div>
                </div>

                {/* Clip results — Strand card list: border-border, hover:bg-card, active accent */}
                <div className="divide-y divide-border bg-background max-h-[280px] overflow-y-auto">
                  {searchClips.map((clip, i) => {
                    const isActive = activeClipIdx === i
                    const barPct = maxScore > 0 ? (clip.score / maxScore) * 100 : 0

                    return (
                      <button
                        key={i}
                        type="button"
                        onClick={() => {
                          playerRef.current?.seekTo(clip.start)
                          setActiveClipIdx(i)
                        }}
                        className={`w-full flex items-center gap-3 px-4 py-3 transition-all duration-150 group text-left border-l-[3px] ${
                          isActive
                            ? 'bg-[var(--strand-ui-accent-light)] border-l-[var(--strand-ui-accent)]'
                            : 'border-l-transparent hover:bg-card border-border/50'
                        }`}
                      >
                        {/* Thumbnail — Strand: rounded-lg, border-border, ring on active */}
                        <div className={`w-14 h-10 rounded-lg overflow-hidden shrink-0 bg-card flex items-center justify-center border transition-all duration-150 ${
                          isActive ? 'ring-2 ring-[var(--strand-ui-accent)] border-[var(--strand-ui-accent)]' : 'border-border group-hover:border-[var(--strand-gray-400)]'
                        }`}>
                          {videoId ? (
                            <img
                              src={`${API_BASE}/api/videos/${encodeURIComponent(videoId)}/frame?t=${clip.start}`}
                              alt=""
                              className="w-full h-full object-cover"
                              loading="lazy"
                              onError={(e) => {
                                const el = e.currentTarget
                                el.style.display = 'none'
                                const fallback = el.nextElementSibling as HTMLElement
                                if (fallback) fallback.style.display = 'flex'
                              }}
                            />
                          ) : null}
                          <span className="w-full h-full items-center justify-center text-text-tertiary" style={{ display: videoId ? 'none' : 'flex' }}>
                            <svg className="w-5 h-5" viewBox="0 0 12 12" fill="currentColor" aria-hidden>
                              <path d="M3 1.5v9l7.5-4.5L3 1.5z" />
                            </svg>
                          </span>
                        </div>

                        {/* Rank + time — Strand typography */}
                        <div className="flex-1 min-w-0 flex items-baseline gap-2">
                          <span className={`text-xs font-semibold tabular-nums shrink-0 ${
                            isActive ? 'text-[var(--strand-ui-accent-hover)]' : 'text-text-tertiary'
                          }`}>
                            {i + 1}
                          </span>
                          <span className="font-brand text-sm font-semibold tabular-nums text-text-primary">
                            {fmtSec(clip.start)}<span className="text-text-tertiary mx-1">–</span>{fmtSec(clip.end)}
                          </span>
                          <span className="text-[10px] font-medium uppercase tracking-wider text-text-tertiary shrink-0">
                            {clip.type}
                          </span>
                        </div>

                        {/* Score bar + percentage — Strand card-style track */}
                        <div className="w-[88px] shrink-0 flex items-center gap-2">
                          <div className="flex-1 h-[5px] rounded-full bg-card overflow-hidden border border-border/50">
                            <div
                              className={`h-full rounded-full transition-all duration-300 ${scoreBarColor(clip.score)}`}
                              style={{ width: `${barPct}%` }}
                            />
                          </div>
                          <span className={`text-xs font-semibold tabular-nums w-[38px] text-right ${
                            isActive ? 'text-[var(--strand-ui-accent-hover)]' : clipScoreColor(clip.score)
                          }`}>
                            {(clip.score * 100).toFixed(1)}%
                          </span>
                        </div>
                      </button>
                    )
                  })}
                </div>

                {/* Timeline — Strand: bg-card, border-border, text-text-secondary */}
                {timelineEnd > 0 && (
                  <div className="px-4 py-3 bg-card border-t border-border">
                    <p className="text-[10px] font-semibold text-text-tertiary uppercase tracking-wider mb-2">
                      Clip positions
                    </p>
                    <div className="relative h-[6px] rounded-full bg-[var(--strand-gray-200)] overflow-visible border border-border/50">
                      {searchClips.map((clip, i) => {
                        const leftPct = (clip.start / timelineEnd) * 100
                        const widthPct = Math.max(((clip.end - clip.start) / timelineEnd) * 100, 1.2)
                        const isActive2 = activeClipIdx === i
                        return (
                          <button
                            key={i}
                            type="button"
                            onClick={() => {
                              playerRef.current?.seekTo(clip.start)
                              setActiveClipIdx(i)
                            }}
                            className={`absolute top-0 h-full rounded-sm cursor-pointer transition-all duration-150 ${
                              isActive2 ? 'ring-2 ring-[var(--strand-ui-accent)]/50 scale-y-[1.6] z-10' : 'hover:scale-y-[1.4] z-0'
                            } ${scoreBarColor(clip.score)}`}
                            style={{ left: `${leftPct}%`, width: `${widthPct}%` }}
                            title={`${fmtSec(clip.start)} – ${fmtSec(clip.end)}`}
                          />
                        )
                      })}
                    </div>
                    <div className="flex justify-between mt-1.5">
                      <span className="text-[10px] text-text-tertiary tabular-nums">0:00</span>
                      <span className="text-[10px] text-text-tertiary tabular-nums">{fmtSec(timelineEnd)}</span>
                    </div>
                  </div>
                )}
              </div>
            )
          })()}

          <div className="rounded-lg border border-gray-300 bg-surface shadow-sm overflow-hidden flex flex-col min-h-0 shrink-0">
            <div className="flex items-center justify-between px-3 sm:px-4 py-3 border-b border-border shrink-0">
              <div className="flex items-center gap-2">
                <svg className="w-4 h-4 text-gray-500" viewBox="0 0 12 11" fill="currentColor">
                  <path d="M1 1H11V2H1V1Z" />
                  <path d="M1 4H9V5H1V4Z" />
                  <path d="M1 7H11V8H1V7Z" />
                  <path d="M1 10H7V11H1V10Z" />
                </svg>
                <h4 className="text-base font-semibold text-gray-700">Transcript</h4>
              </div>
              <span className="text-xs text-gray-400">{videoAnalysis.transcript.length} segments</span>
            </div>
            <ul className="overflow-y-auto divide-y divide-gray-100">
              {(() => {
                const segments = videoAnalysis.transcript
                const visible = (isLgViewport || showAllTranscript) ? segments : segments.slice(0, 2)
                const last = segments.length > 0 ? segments[segments.length - 1] : null
                const lastSec = last ? parseTimestampToSeconds(last.time) : NaN
                const incomplete = segments.length > 0 && videoDurationSec > 0 && Number.isFinite(lastSec) && lastSec < videoDurationSec - 30
                return (
                  <>
                    {visible.map((line, i) => {
                      const seekSeconds = parseTimestampToSeconds(line.time)
                      const handleSeek = () => {
                        if (!Number.isFinite(seekSeconds)) return
                        const player = playerRef.current
                        if (player) player.seekTo(seekSeconds)
                      }
                      return (
                        <li key={i} className="list-none">
                          <button
                            type="button"
                            onClick={handleSeek}
                            className="flex gap-3 px-3 sm:px-4 py-3 hover:bg-card transition-colors duration-150 cursor-pointer w-full text-left border-0 bg-transparent"
                          >
                            <span className="text-xs font-mono text-accent font-medium shrink-0 pt-0.5 w-9">
                              {line.time}
                            </span>
                            <span className="text-sm text-gray-600 leading-relaxed">{line.text}</span>
                          </button>
                        </li>
                      )
                    })}
                    {incomplete && last && (
                      <li className="border-t border-gray-100 px-3 sm:px-4 py-3 flex flex-col items-stretch gap-2 list-none">
                        {appendTranscriptError && (
                          <p className="text-sm text-error text-center w-full" role="alert">{appendTranscriptError}</p>
                        )}
                        <button
                          type="button"
                          onClick={() => appendTranscriptFrom(lastSec)}
                          disabled={appendTranscriptLoading}
                          className="inline-flex items-center justify-center gap-2 rounded-lg px-4 py-2 text-sm font-medium text-accent hover:bg-accent/5 transition-colors disabled:opacity-50 disabled:cursor-not-allowed w-full sm:w-auto self-center"
                        >
                          {appendTranscriptLoading ? (
                            <>
                              <img src={spinnerIconUrl} alt="" className="w-4 h-4 animate-spin shrink-0" aria-hidden />
                              Appending…
                            </>
                          ) : (
                            <>
                              <svg className="w-4 h-4 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden>
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                              </svg>
                              Append transcript from {last.time} to end
                            </>
                          )}
                        </button>
                      </li>
                    )}
                  </>
                )
              })()}
            </ul>
            {videoAnalysis.transcript.length > 2 && !isLgViewport && (
              <div className="shrink-0 border-t border-gray-100 px-3 sm:px-4 py-3 flex justify-center">
                <button
                  type="button"
                  onClick={() => setShowAllTranscript((v) => !v)}
                  className="inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium text-accent hover:bg-accent/5 transition-colors"
                >
                  {showAllTranscript ? (
                    <>
                      <svg className="w-4 h-4 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden>
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
                      </svg>
                      Show less
                    </>
                  ) : (
                    <>
                      <svg className="w-4 h-4 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden>
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                      </svg>
                      Show more ({videoAnalysis.transcript.length - 2} more)
                    </>
                  )}
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
      {linkAnalysisPersonId !== null && linkDataByEntity[linkAnalysisPersonId] && (() => {
        const linkData = linkDataByEntity[linkAnalysisPersonId]
        const person = people.find((p) => p.id === linkAnalysisPersonId)
        const personFaceBase64 = linkData.personFaceBase64 ?? person?.face_from_video_base64
        return (
          <LinkAnalysisModal
            open
            onClose={() => setLinkAnalysisPersonId(null)}
            data={{ ...linkData, personFaceBase64 }}
            onSeekToTime={(seconds) => playerRef.current?.seekTo(seconds)}
          />
        )
      })()}
    </div>
  )
}
